/**
 * Exemplar model answers for each extended question, used for:
 * - offline mode (self-marking against a banded rubric)
 * - the "show me a model answer" flow after AI marking
 * These are exemplars written at roughly Level 3 standard.
 */
const MODEL = {
  'p1-great-expectations': {
    q2: 'The writer piles up verbs and adjectives to make the stranger seem barely human. The noun phrase "a fearful man, all in coarse grey" immediately places him outside normal society, while the list of participles — "soaked", "smothered", "lamed", "cut", "stung", "torn" — overwhelms the reader with what he has suffered. The verbs "limped", "shivered", "glared" and "growled" pair animal sounds with human shape, and the detail that his teeth "chattered in his head" makes his fear audible. Dickens ends with the man "seizing" Pip by the chin: the violent physical contact is sudden, and the reader feels as trapped as Pip.',
    q3: 'The extract opens with a long, brooding description of the marshes, establishing loneliness before any action happens. Dickens then shifts abruptly into dialogue — "Hold your noise!" — a violent interruption that mirrors Pip\u2019s shock. The middle of the text is a single extended description of the convict, piling clause on clause so that the reader, like Pip, cannot look away. Structurally, the writer widens fear outward at the end: the man is not alone, "there\u2019s a young man hid with me", and the threat extends into the future ("will softly creep and creep") — so the extract ends on suspense, forcing us to read on.',
    q4: 'I strongly agree with the statement. The convict provokes terror — "I\u2019ll cut your throat" and the threat to "tear him open" are genuinely disturbing — but Dickens deliberately balances the horror with pity. The list of his injuries ("lamed by stones", "torn by briars") shows us a man broken by suffering, and details like his chattering teeth reveal fear beneath the aggression. His methodical threats even whisper vulnerability; he is out on the marsh, starving, "all in coarse grey", hunted. The writer makes us see the convict as Pip sees him — a monster who is also a victim — and this double impression is what makes the passage so memorable.',
    q5plan: 'Option: description of a threatening place.\n\nPara 1 — Zoom in on ONE detail (a gate, a light, a sound). Start with a short, blunt sentence for tension.\nPara 2 — The senses: what can be heard (wind through a fence, a dog far off), smelled (damp earth), felt (cold on the face).\nPara 3 — Shift to what is MISSING — the silence, the absence of people — and how that absence presses in.\nPara 4 — A hint of movement; something not quite seen. End on a sentence that holds the sense of dread.\n\nThroughout: metaphors (the dark "leaning in"), personification of the landscape, varied sentence lengths for pace.',
  },
  'p1-war-of-the-worlds': {
    q2: 'Wells makes the Martian horrifying by pairing precise anatomical nouns — "brow ridges", "wedge-like lower lip", "tentacles" — with adjectives that undermine them: "peculiar", "incessant", "tumultuous". The assonance and emphasis of "vital, intense, inhuman, crippled and monstrous" builds a rhythm of disgust, climaxing in the one-word judgement "monstrous". The simile-like phrase "something fungoid in the oily brown skin" links the creature to decay and disease, and the narrator\u2019s direct confession — "overcome with disgust and dread" — licenses the reader\u2019s own revulsion, turning observation into horror.',
    q3: 'Wells telescopes his structure from the cosmic to the physical. The opening paragraph establishes a god-like overview of the whole earth, then "yet" pivots the reader toward the enemy, and finally the extract drops to a single roadside encounter: one man, one machine, one "disgust and dread". This narrowing focus — universe, enemy, creature, man — mirrors a lens zooming in, and the tension rises as the scale shrinks. The closing image of the cylinder "rising slowly and painfully" is left unresolved, deliberately structuring the ending as a hook rather than a conclusion.',
    q4: 'I agree that the contrast is the extract\u2019s engine. Humanity is presented with ironic grandeur — "infinite complacency", "serene in their assurance of their empire over matter" — a confidence the reader already knows is about to be destroyed, which creates dramatic irony. Against this self-satisfaction, the Martians are "vast and cool and unsympathetic", their calm a mirror of ours but superior in scale. The physical description then deflates us further: we are examined like "creatures in a drop of water". The writer makes the invasion terrifying precisely because the one thing humanity is sure of — its own importance — is the illusion the text dismantles, sentence by sentence.',
    q5plan: 'Option: story about a discovery that changes everything.\n\nPara 1 — Establish normal life with one vivid, ordinary detail (a breakfast, a walk, a chore).\nPara 2 — The discovery begins small: an object, a sound, a mark. Misdirect the reader slightly.\nPara 3 — Reveal the truth gradually through the character\u2019s reactions; let dialogue carry the shock.\nPara 4 — Consequences start to ripple — what changes first? End on a question or a threatening image.\n\nThroughout: contrast calm and alarm, use short sentences for shock inside longer descriptive ones.',
  },
  'p1-jane-eyre': {
    q2: 'Brontë\u2019s language makes the red-room both luxurious and prison-like. The repetition of "red" — red damask, crimson cloth, the red carpet — saturates the room with the colour of danger and blood, while "chill", "silent" and "solemn" build an air of ritual and death. The simile comparing the bed to "a tabernacle" is almost religious, making the room a place of judgement rather than rest. Yet the description is also claustrophobic: the windows are "shrouded" and "blinds always drawn down", cutting off light and escape. Even the white bed, "like a pale throne", suggests power, not comfort — a place where an accused child is displayed, not slept.',
    q3: 'The extract is structured as a physical and emotional descent. It begins outside with the cold garden and the word that sets the tone, "chill", then moves inside, deeper and deeper — from the sitting-room, to the window seat, and finally to the red-room itself, the house\u2019s heart of secrets. The sentences grow temporarily longer and more ornamental as Brontë inventories the furniture, slowing time the way a frightened child experiences it. The writer saves the triple judgement — "chill... silent... solemn" — for the end, so the extract closes by sealing Jane in, and the structure itself becomes the trap.',
    q4: 'I agree that loneliness and powerlessness are the extract\u2019s core feelings. Jane is excluded by the weather, by the family ("Mrs. Reed... dined early"), and by her body, which she is taught is "inferior". Brontë keeps her almost voiceless — the entire passage is her watching, never her speaking. The house offers hiding places, but they only deepen her solitude: the window seat withdraws her from the family, and the red-room is where she will literally be locked in. The writer links powerlessness to space itself: every room Jane enters belongs to someone else. The passage persuades us not through argument but by making us feel the architecture of a childhood without welcome.',
    q5plan: 'Option: description of a room with a strange atmosphere.\n\nPara 1 — Name the room in a single sentence and note what it is used for (or that it is never used).\nPara 2 — Colour and light: describe what enters and what is kept out.\nPara 3 — Texture and memory: objects that hold stories; a smell, a layer of dust.\nPara 4 — The room\u2019s effect on the person inside; end with what it makes them feel.\n\nThroughout: personify the room ("the room waited"), layer sensory detail rather than listing it.',
  },
  'p1-treasure-island': {
    q2: 'Stevenson assembles the captain from ragged, tactile details: "tarry pigtail", "soiled blue coat", "hands ragged and scarred, with black, broken nails". These compound noun phrases do double work — each one gives the reader a picture AND a judgement. The simile hidden in "a bit of stick like a handspike" quietly makes him seem half-sailor, half-weapon, and even his singing is described as a "high, old tottering voice... tuned and broken at the capstan bars", as if the ship has worn grooves into the man himself. The word "scathed"? Nothing is pretty; every verb he performs — plodding, rapping, glaring — is heavy and threatening, so that danger arrives before he says a word.',
    q3: 'Stevenson structures the extract as a series of arrivals, each one darker than the last. It opens with the memorable framing "I remember him as if it were yesterday", which plants the extract in memory and signals that what follows matters. The arrival at the door is comic — the song, the rum, the toast to the "sittyated grog-shop" — but the writer then folds in the sinister: the payment for watching for a one-legged man, and the narrator\u2019s "thousand diabolical" dreams. The final paragraph converts comedy into routine menace — "the fierce routine of his habits" — and the ending image of the captain "glaring into the dark" leaves the reader unsettled and curious.',
    q4: 'I agree that the captain balances comedy and terror. Comedy flows from exaggeration — the deafening rum-drinking, the enormous sunburned face, the pretence of manners ("Much company, mate?") — yet Stevenson undercuts every laugh with threat: the song erupts from the same mouth that shouts for rum, and the boy who is paid a "silver fourpenny" is being groomed to watch for a man the captain clearly fears. The dreams of the one-legged seafarer turn the payment sour. By alternating joviality with menace so smoothly, the writer creates a character we can neither trust nor ignore — the longest-lasting kind of villain.',
    q5plan: 'Option: story about a secret a child is paid to keep.\n\nPara 1 — The transaction: who, what, how much. Make the bribe small and specific.\nPara 2 — The child\u2019s attempts to act normally, and the details they begin to notice around them.\nPara 3 — A test: something almost happens; the secret nearly surfaces. Quicken the pace.\nPara 4 — A resolution where the child must choose; end on the moment of decision or its cost.\n\nThroughout: first-person voice, concrete coins/details, short sentences under pressure.',
  },
  'p1-dracula': {
    q2: 'Stoker builds fear through sound before anything is seen. The wolves\u2019 howl is first "a sound so faint at first that it might have been the wind in the pines" — the simile delays the threat, and the oxymoron "sorrowful and cruel" makes the noise feel unnatural. His physical response — "my blood seemed to freeze in my veins" — transfers the fear into the body. The blue flames, "as though the night itself were lighting little lamps", are described as beautiful before the driver explains they mark graves, so beauty converts abruptly into dread. Throughout, the similes (the carriage "rocking like a ship on a stormy sea") keep the landscape unstable, and the final metaphor of the castle as "a crouching beast" turns architecture into predator.',
    q3: 'Stoker structures the extract as one long increase in pressure, measured in stages: unease at dusk, the first howl, the wolves\u2019 chorus, the ghost-lights, and finally the castle. Each stage is introduced by a specific marker of time ("As the evening fell...", "Then, far off in the darkness...", "Suddenly..."), which acts like a drumbeat counting the reader toward the climax. The writer also uses interruptions — the driver\u2019s calm explanations — to slow the terror down, making the relief momentary and the fear stronger afterwards. The extract ends by landing, literally and emotionally, at the foot of the castle, so the entire journey becomes a funnel aimed at one building.',
    q4: 'I agree that the landscape is animated until it feels alive. The trees "lean closer as we went", the twilight "merges" into darkness, and the night "lighting little lamps" becomes a purposeful, watching figure. This personification matters because Jonathan\u2019s fear is never of a named enemy — only of place. The writer keeps the source of danger off-stage: the wolves are heard, the dead are only implied, the castle is "ruined" and unlit. By making the environment itself predatory, Stoker traps the character and reader in a world where everything — the soil, the sky, the stones — is potentially hostile, which is precisely the effect he needs for a novel about an ancient evil embedded in the land.',
    q5plan: 'Option: a night journey to somewhere you have never been.\n\nPara 1 — The departure: describe the last familiar landmark disappearing.\nPara 2 — Darkness and unexpected sounds; your reaction (heart, breathing).\nPara 3 — A false alarm — a sound explained — then the real unexplained thing.\nPara 4 — Arrival; describe the place in one final, unsettling image (like the "crouching beast").\n\nThroughout: verbs of movement, similes that compare the journey to a ship at sea, sensory overload then sudden silence.',
  },
  'p1-frankenstein': {
    q2: 'Shelley turns anatomy into horror through contrast. The creature\u2019s features are individually lovely — "lustrous black... flowing" hair, teeth "of a pearly whiteness" — but the conjunction "but" pivots each beauty into repulsion: the skin is "yellow", "scarcely covered" the muscles, the eyes are "watery", "dun-white sockets", "shrivelled complexion... straight black lips". The chiasmus "Beautiful! Great God!" shows Victor\u2019s mind breaking mid-sentence, and the adjectives of decay — "dun", "shrivelled", "dismally" — saturate the passage. The monster is described entirely as a list of parts, never a whole person, so the language itself performs Victor\u2019s failure to see his creation as anything but a catalogue of horrors.',
    q3: 'The structure performs the reversal it describes. It begins at the peak of excitement — "the accomplishment of my toils" — with the creation itself paused in the middle sentence as the eye opens. Shelley then moves into retrospective judgement: the long second paragraph looks back ("How can I describe...") while the third collapses the entire two-year project into a single disillusionment, "the beauty of the dream vanished". Finally, the extract escapes the room with Victor, running, and the pace of the verbs — "rushed", "traversed" — contrasts with the slowness of ruin. The closing dreams in italics of thought leave the horror unfinished, so the structure ends inside Victor\u2019s head, where the creature will stay.',
    q4: 'I agree, but only up to a point. Sympathy is created through Victor\u2019s genuine agony — he has "deprived myself of rest and health" — and through the honesty of his confession: he calls the event a "catastrophe" and blames no one but himself. Yet the language keeps undermining that sympathy: the creature is "the wretch", "the being", "it" — never once "he". Victor\u2019s terror drives him to abandon what he made within minutes of its birth, and the reader senses the cruelty inside the self-pity. The writer therefore creates a complicated sympathy: we pity Victor\u2019s horror, but the passage quietly asks whether horror excuses cruelty. It is the question, more than the answer, that makes the extract powerful.',
    q5plan: 'Option: a long-awaited success turning to disaster.\n\nPara 1 — The final moment of expectation: hands, breath, a countdown, a door about to open.\nPara 2 — Success arrives — describe it in rich, golden language.\nPara 3 — The turn: ONE small detail that is wrong, then another, then the collapse.\nPara 4 — The aftermath: what is left, and what the character feels (contrast with para 2).\n\nThroughout: echo words from the opening at the end; use light/weather as a barometer of feeling.',
  },
  'p2-schools': {
    q2: 'The two texts present schools as opposites: one prises facts, the other prizes attention and conversation. In Source A, Gradgrind demands "Facts alone are wanted in life" and the boys and girls are treated as "little vessels... ready to have imperial gallons of facts poured into them" — learning is passive, mechanical, obedient. Sissy must even give up her name. In Source B, the school ban on phones produces "improved listening", long loud conversations in the dining hall and a pupil who starts keeping "a real paper" notebook; learning here is active, social and personal. Where the first school forbids, the second transforms; where the first fills children up, the second frees them.',
    q3: 'The writer uses conversational self-deprecation and concrete detail to sound honest and likeable. The opening claim — "I laughed — genuinely, out loud, in the middle of registration" — establishes a sceptical voice the reader can trust, and the turn "I discovered something awkward: I didn\u2019t know how to do it any more" admits fault, which makes the later praise believable. The simile of collecting phones "like pilots collecting passports" elevates an ordinary routine into something faintly heroic and funny. Single-sentence paragraphs such as "I am not saying the world changed. But the air in our building changed" use sharp contrast to land the argument, as does the final metaphor that the "world is bigger than the size of a screen" — a plain image that makes the conclusion feel inevitable.',
    q4: 'Both writers are sceptical about how schools treat children, but in opposite directions. Dickens\u2019 goal is to attack a system that crushes individuality — he uses a satirical, exaggerated authority figure (the "square" Gradgrind with his "square wall of a forehead") and comic imagery of children as "vessels", so that the schoolroom feels mechanical and the children invisible. The modern writer is warmer and funnier, using first-person anecdote to show how a restriction actually restored individuality. Dickens judges through coldness; the modern writer persuades through warmth. Both, however, make the same underlying claim: what a school chooses to value — facts or attention — shapes the kind of person its pupils become.',
    q5plan: 'Article arguing AGAINST phones in schools.\n\nPara 1 — Anecdote: a lesson derailed by a notification; generalize from it.\nPara 2 — Address the counter-argument directly: "Some say phones teach digital skills..." then rebut.\nPara 3 — Evidence-style reasoning: attention, memory, social confidence; the dining-hall test.\nPara 4 — A solution of the middle ground (lockers, pouches, phone-free hours).\nEnd — Rhetorical question + a short, forceful final sentence.\n\nDevices: rule of three, rhetorical questions, direct address ("you know the feeling"), first-person honesty.',
  },
  'p2-weather': {
    q2: 'The two writers describe extreme city weather, but where Dickens\u2019 fog paralyses and connects Londoners, the modern heat isolates and convicts them. In Source A the fog is everywhere and touches everyone — pensioners, skippers, apprentice boys, passers-by — creating a shared, comic-grotesque misery of jostling umbrellas and "slipping and sliding" feet. The modern writer is instead closed up indoors, curtains "shut like eyelids", and the street is "holding its breath"; people meet only briefly, as with the old man and his thermometer-like judgement. Dickens\u2019 weather is an event to survive; Source B\u2019s heat becomes an accusation — a week that "interrupts" but does not change anyone.',
    q3: 'The writer personifies the heat into a being that touches, presses and punishes. "A hand pressing on the back of my neck" makes the temperature physical and intimate, while the street that is "holding its breath" turns the city into a single anxious body. Similes built from ordinary life — footprints "like footprints on a beach", curtains "like eyelids", the newspaper "flannel" — root the strangeness in familiar things, which makes it believable. The ending shifts register into plain, declarative sentences: "It does not shout; it simply turns the dial, one notch per summer." The metaphor of the dial compresses the whole argument about climate into one mechanical image, and the closing question hands the responsibility squarely to the reader.',
    q4: 'Dickens\u2019 viewpoint is detached, observational and darkly amused: the fog is a spectacle that "comes mourning for the death of the sun", and the narrator enjoys the chaos of umbrellas and ill-temper. The modern writer\u2019s viewpoint is urgent and self-critical, using first-person experience to accuse "we... still drove two separate cars". Dickens uses anaphora — the relentless repetition of "Fog..." clauses — to smother the reader in the weather; the modern writer uses short, blunt sentences ("It did, somehow.") to create the same pressure by restraint. The essential difference is time: Dickens presents weather as timeless comedy, while Source B insists it is a symptom of something the reader must act on — entertainment versus alarm.',
    q5plan: 'Speech arguing that individuals DO make a difference.\n\nOpening — Address the assembly directly; concede the truth (one person cannot stop a heatwave).\nPara 2 — Reframe: individual choices aggregate — "a million dials turned down, one notch each".\nPara 3 — Concrete examples from daily life (meat-free days, one-car trips, switched-off plugs) with calm verbs, not sermons.\nPara 4 — Answer the strongest counter-argument ("the real polluters are companies") by showing how consumer choices steer them.\nEnd — A repeated refrain phrase + a direct call to one action THIS week.\n\nDevices: rule of three, inclusive pronouns (we, our), anaphora of "when you...", contrast, and a rhetorical question to close.',
  },
  'p2-city': {
    q2: 'Both writers enter the town resentfully, but their destinations are opposites. In Source A, Margaret approaches Milton under "a deep lead-coloured cloud" through streets that are "long and straight" and houses "uniform, and unpicturesque"; the city is a factory first and a home nowhere, its people hurried and drained ("quick, sharp, and unaccustomed to rest"). The modern writer leaves a city of nine million to reach a village of forty-three, whose shop "closes at noon for reasons nobody can explain" and whose mobile library is the week\u2019s main event. For Gaskell, Milton is a place of noise, smoke and hollow cheeks; for the blogger, the city was nine million strangers — and the village, however inconvenient, restores sleep and time.',
    q3: 'The writer uses lists and rhythmic exaggeration to make city life feel bruising. The list of what she knows — "five colleagues, four flatmates, a barista called Grace" — is comic precisely because it is so small against "nine million people", and the detail of the neighbour\u2019s name learned "from his post" turns loneliness into a visual joke. The invented condition — "the particular flavour of despair you only taste at 11:40pm on a bus that has not moved for twenty minutes" — compresses time, place and feeling into one phrase. Against this, the village is described with gentle, slowed imagery: silence so complete "I could hear my own blinking", and morning light "down the valley like a poured drink" — language that itself slows the reader down.',
    q4: 'Gaskell views the industrial city with controlled dread: she describes it from the outside, through Margaret\u2019s journey, so the reader sees the cloud and hears the looms before meeting anyone. Her viewpoint is social — she indicts the conditions that hollow people out ("hollow cheeks", the running children). The modern writer takes the personal route: city life is judged by its effect on one person\u2019s sleep, and the argument is carried by anecdote and laughter. Both writers use sensory overload as evidence — Gaskell\u2019s "tapping and hammering and clashing" looms, the blogger\u2019s "noise... escalators that moved slower than my own legs" — but Gaskell mourns the workers, while the modern writer rescues herself. Their viewpoints differ in exit: one cannot leave, the other does.',
    q5plan: 'Letter arguing city life is NOT bad for you.\n\nOpening — Friendly direct address; establish shared experience ("you remember the flat...").\nPara 2 — Concede: yes, noise, rent and tiredness are real. Be honest, not defensive.\nPara 3 — Counter with what the city gives: anonymity, opportunity, food, ideas, people unlike yourself.\nPara 4 — Balance: it is not city vs country, but how you live in either.\nEnd — Invite them to visit; close warmly with a single striking sentence.\n\nDevices: anecdote, concession-then-rebuttal structure, lists of vivid details, direct address.',
  },
  'p2-work': {
    q2: 'The two texts describe being denied what you need, but the denial looks different in each. In Source A the workhouse makes starvation formal: boys receive one bowl each "and no more", under a master who turns "very pale" at the unthinkable request for extra. The cruelty is official, public, even legal. In Source B poverty is quieter and modern: nothing is refused, but everything costs attention — "the heating bill you will not open, the dentist you will not call". The Victorian hunger is simple and physical; the modern hardship is a thousand small calculations. Both writers show that the system punishes the poor twice: Dickens by rationing food, the journalist by rationing choice.',
    q3: 'The writer makes poverty tangible through prices and small objects. Exact numbers — eleven pence a slice, "£2.14" — set the terms of a week where everything is arithmetic, and the simile of running sums "the way other people scroll their phones" turns mental maths into an addiction and a prison. Personification gives the bills a character ("the heating bill you will not open"), and the missing table becomes a parable: "a decision about what matters, and you cannot afford to get that decision wrong". The ending repository of the bootstraps metaphor is devastating because it is physically literal — "you cannot lift yourself by your own boots" — converting a cheerful cliché into a small, accurate lesson about dependency.',
    q4: 'Dickens\u2019s viewpoint is fiercely satirical: he sides openly with Oliver and ridicules the establishment — the master "clung for support to the copper", the gentleman in the white waistcoat predicts Oliver "will be hung". Irony is the main method: calling gruel a "festive composition" and the workhouse officials "paralysed with wonder" exposes cruelty through mockery. The modern writer\u2019s viewpoint is personal and measured, built on lived experiment rather than fiction, appealing through empathy instead of satire. Where Dickens takes one symbolic moment — the asking for "more" — the journalist accumulates a week of quiet deferrals. Both writers are angry; one shouts through comedy, the other speaks through numbers. Together they argue that how society treats its poorest is a moral test it keeps failing across the centuries.',
    q5plan: 'Article agreeing that work must pay enough to live on.\n\nOpening — A striking statistic or a vignette of a working person; state your position in one line.\nPara 2 — Reason one: dignity — work is a contract, not a favour; fair pay is basic decency.\nPara 3 — Reason two: cost to everyone — poverty wages are subsidised by food banks and emergency services; we all pay.\nPara 4 — Address the counter-arguments ("higher wages cost jobs", "businesses can\u2019t afford it") and answer each.\nEnd — A call to action: what readers/employers should do; close on a short, memorable sentence.\n\nDevices: rhetorical questions, rule of three, emotive but precise language, direct address.',
  },
};

export function exemplarsFor(id) {
  return MODEL[id] || {};
}