import { useFocusEffect, router } from 'expo-router';
import { useCallback, useState } from 'react';
import { Text, View } from 'react-native';
import { ApiClient } from '@/api';
import { Button, DeskHeader, Notice, ScrollScreen, SectionHeader } from '@/components';
import { useAuth, usePreferences } from '@/providers';
import { advanceMistake, dueMistakes, type MistakeRow } from '@/notebook';
import { hydratePersonal } from '@/personal';
import { useTheme } from '@/theme';

export default function Notebook(){const {session}=useAuth();const {subject}=usePreferences();const {colors,subject:tokens}=useTheme();const [rows,setRows]=useState<MistakeRow[]>([]);const [loaded,setLoaded]=useState(false);const [error,setError]=useState('');const client=new ApiClient(subject);useFocusEffect(useCallback(()=>{let active=true;setLoaded(false);setError('');hydratePersonal(client,session?.user.id,subject).then(personal=>{if(!active)return;setRows(personal.mistakes);setLoaded(true)}).catch(()=>{if(!active)return;setError('The notebook could not be loaded. Check your connection and try again.');setLoaded(true)});return()=>{active=false};
// The client is scoped to the active subject; reload whenever either identity changes.
// eslint-disable-next-line react-hooks/exhaustive-deps
},[session?.user.id,subject]));const visible=rows.filter(row=>!row.mastered);const due=new Set(dueMistakes(visible).map(row=>row.id));async function reviewed(id:string){const next=advanceMistake(rows,id);setRows(next);try{await client.saveMistakes(next)}catch(cause){setError(cause instanceof Error?`Notebook could not be saved: ${cause.message}`:'Notebook could not be saved.')}}return <ScrollScreen><DeskHeader title="Mistake notebook" eyebrow="ACCOUNT STUDY RECORD"/><Notice title="HOW THIS WORKS">Incorrect rows are copied from server marking and saved to your account. Review dates at 1, 3, 7 and 21 days are planning prompts, not server progress.</Notice>{error&&<Notice kind="error" title="ACTION NOT COMPLETED">{error}</Notice>}<SectionHeader title="Captured mistakes" meta={`${due.size} DUE / ${visible.length} SAVED`}/>{!loaded&&<Notice kind="loading" title="LOADING NOTEBOOK">Reading your saved mistakes.</Notice>}{loaded&&visible.length===0&&<Notice title="NOTEBOOK CLEAR">Incorrect server-marked result rows will appear here after a submission.</Notice>}{visible.map(row=>{const reviewIndex=row.reviewIndex??0;const dueDate=row.dueDates?.[reviewIndex];return <View key={row.id} style={{borderWidth:1,borderLeftWidth:due.has(row.id)?6:1,borderColor:due.has(row.id)?tokens.accent:colors.strong,backgroundColor:colors.raised,padding:14,gap:8}}><Text style={{fontFamily:'monospace',fontSize:11,fontWeight:'800',color:tokens.accent}}>{due.has(row.id)?'DUE TO RETRY':'SCHEDULED'} / {row.topicName}</Text><Text style={{fontFamily:'serif',fontSize:20,color:colors.ink}}>{row.prompt}</Text>{row.answer!==undefined&&<Text style={{color:colors.quiet}}>Your answer: {typeof row.answer==='string'?row.answer:JSON.stringify(row.answer)}</Text>}{dueDate&&<Text style={{color:colors.quiet}}>Next review: {new Date(dueDate).toLocaleDateString()}</Text>}{row.topicId&&<Button variant="secondary" onPress={()=>router.push({pathname:'/practice',params:{topicId:row.topicId}})}>RETRY THIS TOPIC</Button>}<Button variant="secondary" onPress={()=>void reviewed(row.id)}>{reviewIndex>=row.dueDates.length-1?'MARK MASTERED':'I RETRIED THIS'}</Button></View>})}</ScrollScreen>}