import AsyncStorage from '@react-native-async-storage/async-storage';
import { useFocusEffect, router } from 'expo-router';
import { useCallback, useState } from 'react';
import { Text, View } from 'react-native';
import { Button, DeskHeader, Notice, ScrollScreen, SectionHeader } from '@/components';
import { useAuth, usePreferences } from '@/providers';
import { advanceMistake, dueMistakes, notebookKey, type MistakeRow } from '@/notebook';
import { useTheme } from '@/theme';

export default function Notebook(){const {session}=useAuth();const {subject}=usePreferences();const {colors,subject:tokens}=useTheme();const [rows,setRows]=useState<MistakeRow[]>([]);useFocusEffect(useCallback(()=>{let active=true;AsyncStorage.getItem(notebookKey(session?.user.id)).then(raw=>{try{const parsed=JSON.parse(raw??'[]');if(active)setRows(Array.isArray(parsed)?parsed:[])}catch{if(active)setRows([])}});return()=>{active=false}},[session?.user.id]));const visible=rows.filter(row=>row.subject===subject&&(row.reviewIndex??0)<row.due.length);const due=new Set(dueMistakes(visible).map(row=>row.id));async function reviewed(id:string){const next=advanceMistake(rows,id);setRows(next);await AsyncStorage.setItem(notebookKey(session?.user.id),JSON.stringify(next))}return <ScrollScreen><DeskHeader title="Mistake notebook" eyebrow="DEVICE STUDY RECORD"/><Notice title="HOW THIS WORKS">Incorrect rows are copied from cached server marking. Review dates at 1, 3, 7 and 21 days are planning prompts, not server progress.</Notice><SectionHeader title="Captured mistakes" meta={`${due.size} DUE / ${visible.length} SAVED`}/>{visible.length===0&&<Notice title="NOTEBOOK CLEAR">Incorrect server-marked result rows will appear here after a submission.</Notice>}{visible.map(row=>{const reviewIndex=row.reviewIndex??0;return <View key={row.id} style={{borderWidth:1,borderLeftWidth:due.has(row.id)?6:1,borderColor:due.has(row.id)?tokens.accent:colors.strong,backgroundColor:colors.raised,padding:14,gap:8}}><Text style={{fontFamily:'monospace',fontSize:11,fontWeight:'800',color:tokens.accent}}>{due.has(row.id)?'DUE TO RETRY':'SCHEDULED'} / {row.topicName}</Text><Text style={{fontFamily:'serif',fontSize:20,color:colors.ink}}>{row.prompt}</Text><Text style={{color:colors.quiet}}>Your answer: {typeof row.answer==='string'?row.answer:JSON.stringify(row.answer)}</Text><Text style={{color:colors.quiet}}>Next review: {new Date(row.due[reviewIndex]).toLocaleDateString()}</Text>{row.topicId&&<Button variant="secondary" onPress={()=>router.push({pathname:'/practice',params:{topicId:row.topicId}})}>RETRY THIS TOPIC</Button>}<Button variant="secondary" onPress={()=>void reviewed(row.id)}>{reviewIndex===row.due.length-1?'MARK MASTERED':'I RETRIED THIS'}</Button></View>})}</ScrollScreen>}
