import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { useState, type ReactNode } from 'react';
import { LayoutAnimation, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import Svg, { Circle, G, Line, Path, Polygon, Polyline, Rect, Text as SvgText } from 'react-native-svg';

type Row=Record<string,unknown>;
type Colors=Record<string,string>;
type Point={x:number;y:number;label?:string};
const W=420,H=270,PAD=38;
const SVG_TYPES=new Set(['cartesian','histogram','coordinate','scatter','shape','pie','number-line','range','tally','venn','tree','dot-pattern']);
const row=(value:unknown):Row=>value&&typeof value==='object'&&!Array.isArray(value)?value as Row:{};
const list=(value:unknown):unknown[]=>Array.isArray(value)?value:[];
const number=(value:unknown,fallback=0)=>typeof value==='number'&&Number.isFinite(value)?value:fallback;
const label=(value:unknown)=>typeof value==='string'?value:typeof value==='number'?String(value):'';
const points=(value:unknown):Point[]=>list(value).map(item=>row(item)).map(item=>({x:number(item.x),y:number(item.y),label:label(item.label)||undefined}));
export const stimulusType=(value:unknown)=>label(row(value).type);

export function MathsVisual({stimulus,colors,accent}:{stimulus:unknown;colors:Colors;accent:string}){
  const data=row(stimulus);const type=stimulusType(data);const svg=SVG_TYPES.has(type);const [detail,setDetail]=useState(true);const [expanded,setExpanded]=useState(false);const [selected,setSelected]=useState('');
  if(!type)return null;
  const toggle=(update:()=>void)=>{LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);update()};
  return <View accessible accessibilityRole="image" accessibilityLabel={label(data.alt)||label(data.title)||`${type} supplied with the question`} style={[styles.figure,{borderColor:colors.line,backgroundColor:colors.raised}]}>
    <View style={[styles.stage,svg?{height:expanded?360:230}:{minHeight:expanded?360:230}]}><VisualBody data={data} type={type} colors={colors} accent={accent} detail={detail} selected={selected} setSelected={setSelected}/></View>
    {!!selected&&<View accessibilityLiveRegion="polite" style={[styles.readout,{backgroundColor:colors.infoWash}]}><MaterialCommunityIcons name="cursor-default-click-outline" color={colors.info} size={17}/><Text style={{color:colors.ink,flex:1}}>{selected}</Text></View>}
    <View style={styles.controls}><Pressable accessibilityRole="button" accessibilityState={{selected:detail}} onPress={()=>toggle(()=>setDetail(value=>!value))} style={[styles.control,{borderColor:detail?accent:colors.strong,backgroundColor:detail?colors.muted:colors.raised}]}><MaterialCommunityIcons name={detail?'eye-outline':'eye-off-outline'} color={detail?accent:colors.quiet} size={18}/><Text style={{color:colors.ink,fontWeight:'700'}}>{detail?'Details on':'Details off'}</Text></Pressable><Pressable accessibilityRole="button" accessibilityState={{expanded}} onPress={()=>toggle(()=>setExpanded(value=>!value))} style={[styles.control,{borderColor:colors.strong,backgroundColor:colors.raised}]}><MaterialCommunityIcons name={expanded?'arrow-collapse':'arrow-expand'} color={accent} size={18}/><Text style={{color:colors.ink,fontWeight:'700'}}>{expanded?'Fit':'Enlarge'}</Text></Pressable></View>
  </View>;
}

function VisualBody(props:{data:Row;type:string;colors:Colors;accent:string;detail:boolean;selected:string;setSelected:(value:string)=>void}){
  const {data,type,colors,accent,detail,setSelected}=props;
  if(type==='table')return <TableVisual data={data} colors={colors} accent={accent} setSelected={setSelected}/>;
  if(type==='bar')return <BarVisual data={data} colors={colors} accent={accent} detail={detail} setSelected={setSelected}/>;
  if(type==='counters')return <CountersVisual data={data} colors={colors} setSelected={setSelected}/>;
  if(type==='dice')return <DiceVisual colors={colors} accent={accent} setSelected={setSelected}/>;
  if(type==='pictogram')return <PictogramVisual data={data} colors={colors} accent={accent}/>;
  if(type==='sample-space')return <SampleSpaceVisual data={data} colors={colors} accent={accent} setSelected={setSelected}/>;
  if(type==='probability-scale')return <ProbabilityScale colors={colors} accent={accent}/>;
  return <SvgVisual data={data} type={type} colors={colors} accent={accent} detail={detail} setSelected={setSelected}/>;
}

function GraphFrame({children,colors}:{children:ReactNode;colors:Colors}){return <Svg width="100%" height="100%" viewBox={`0 0 ${W} ${H}`}><Rect x={PAD} y={PAD} width={W-PAD*2} height={H-PAD*2} rx="3" fill={colors.paper} stroke={colors.line}/>{children}</Svg>}
function ticks(min:number,max:number,target:number){const step=Math.max(1,Math.ceil((max-min)/target));const values:number[]=[];for(let value=Math.ceil(min/step)*step;value<=max;value+=step)values.push(value);return values}
function SvgVisual({data,type,colors,accent,detail,setSelected}:{data:Row;type:string;colors:Colors;accent:string;detail:boolean;setSelected:(value:string)=>void}){
  if(type==='cartesian')return <Cartesian data={data} colors={colors} accent={accent} detail={detail} setSelected={setSelected}/>;
  if(type==='histogram')return <Histogram data={data} colors={colors} accent={accent} detail={detail} setSelected={setSelected}/>;
  if(type==='coordinate'||type==='scatter')return <Coordinate data={data} colors={colors} accent={accent} detail={detail} setSelected={setSelected}/>;
  if(type==='shape')return <Shape data={data} colors={colors} accent={accent} detail={detail}/>;
  if(type==='pie')return <Pie data={data} colors={colors} accent={accent}/>;
  if(type==='number-line'||type==='range')return <NumberLine data={data} colors={colors} accent={accent}/>;
  if(type==='tally')return <Tally data={data} colors={colors} accent={accent}/>;
  if(type==='venn')return <Venn data={data} colors={colors} accent={accent}/>;
  if(type==='tree')return <Tree data={data} colors={colors} accent={accent}/>;
  if(type==='dot-pattern')return <DotPattern data={data} colors={colors} accent={accent}/>;
  return <View style={styles.fallback}><MaterialCommunityIcons name="image-filter-center-focus" size={30} color={accent}/><Text style={{color:colors.ink,textAlign:'center'}}>{label(data.alt)||'Structured question diagram'}</Text></View>;
}

function Cartesian({data,colors,accent,detail,setSelected}:{data:Row;colors:Colors;accent:string;detail:boolean;setSelected:(value:string)=>void}){
  const xMin=number(data.xMin,-5),xMax=number(data.xMax,5),yMin=number(data.yMin,-5),yMax=number(data.yMax,5);const sx=(x:number)=>PAD+(x-xMin)/(xMax-xMin||1)*(W-PAD*2);const sy=(y:number)=>H-PAD-(y-yMin)/(yMax-yMin||1)*(H-PAD*2);const xt=ticks(xMin,xMax,10),yt=ticks(yMin,yMax,8);const series=list(data.series).map(row);
  return <GraphFrame colors={colors}>{detail&&xt.map(x=><Line key={`x${x}`} x1={sx(x)} y1={PAD} x2={sx(x)} y2={H-PAD} stroke={colors.line}/>) }{detail&&yt.map(y=><Line key={`y${y}`} x1={PAD} y1={sy(y)} x2={W-PAD} y2={sy(y)} stroke={colors.line}/>) }<Line x1={sx(0)} y1={PAD} x2={sx(0)} y2={H-PAD} stroke={colors.ink} strokeWidth="2"/><Line x1={PAD} y1={sy(0)} x2={W-PAD} y2={sy(0)} stroke={colors.ink} strokeWidth="2"/>{series.map((seriesRow,index)=>{const values=list(seriesRow.points).map(pair=>list(pair)).filter(pair=>pair.length>=2).map(pair=>[number(pair[0]),number(pair[1])]);return <G key={index}><Polyline points={values.map(([x,y])=>`${sx(x)},${sy(y)}`).join(' ')} fill="none" stroke={index?colors.info:accent} strokeWidth="3"/>{values.map(([x,y],pointIndex)=><Circle key={pointIndex} cx={sx(x)} cy={sy(y)} r="8" fill={index?colors.info:accent} opacity=".92" onPress={()=>setSelected(`${label(seriesRow.label)||'Graph'}: (${x}, ${y})`)}/>)}</G>})}{detail&&xt.map(x=><SvgText key={`tx${x}`} x={sx(x)} y={Math.min(H-PAD+17,sy(0)+17)} fontSize="10" fill={colors.quiet} textAnchor="middle">{x}</SvgText>)}{detail&&yt.filter(y=>y!==0).map(y=><SvgText key={`ty${y}`} x={Math.max(PAD-8,sx(0)-8)} y={sy(y)+4} fontSize="10" fill={colors.quiet} textAnchor="end">{y}</SvgText>)}</GraphFrame>;
}

function Histogram({data,colors,accent,detail,setSelected}:{data:Row;colors:Colors;accent:string;detail:boolean;setSelected:(value:string)=>void}){const bars=list(data.bars).map(row);const maxX=Math.max(1,...bars.map(item=>number(item.to)));const maxY=Math.max(1,...bars.map(item=>number(item.height)))*1.15;const sx=(x:number)=>PAD+x/maxX*(W-PAD*2),sy=(y:number)=>H-PAD-y/maxY*(H-PAD*2);return <GraphFrame colors={colors}>{detail&&ticks(0,Math.ceil(maxY),6).map(y=><Line key={y} x1={PAD} y1={sy(y)} x2={W-PAD} y2={sy(y)} stroke={colors.line}/>)}{bars.map((item,index)=>{const from=number(item.from),to=number(item.to),height=number(item.height);return <G key={index} onPress={()=>setSelected(`${from} to ${to}: frequency density ${height}`)}><Rect x={sx(from)} y={sy(height)} width={Math.max(1,sx(to)-sx(from))} height={sy(0)-sy(height)} fill={accent} opacity={detail ? .72 : .5} stroke={colors.ink}/><SvgText x={(sx(from)+sx(to))/2} y={sy(0)+17} fontSize="10" fill={colors.quiet} textAnchor="middle">{from}-{to}</SvgText></G>})}</GraphFrame>}

function Coordinate({data,colors,accent,detail,setSelected}:{data:Row;colors:Colors;accent:string;detail:boolean;setSelected:(value:string)=>void}){const pts=points(data.points),linePts=points(data.line),segments=list(data.segments).map(segment=>points(segment));const all=[...pts,...linePts,...segments.flat()];const xs=all.map(item=>item.x),ys=all.map(item=>item.y);const xMin=number(data.xMin,Math.min(-1,...xs)-1),xMax=number(data.xMax,Math.max(7,...xs)+1),yMin=number(data.yMin,Math.min(-1,...ys)-1),yMax=number(data.yMax,Math.max(7,...ys)+1);const sx=(x:number)=>PAD+(x-xMin)/(xMax-xMin||1)*(W-PAD*2),sy=(y:number)=>H-PAD-(y-yMin)/(yMax-yMin||1)*(H-PAD*2);const xt=ticks(xMin,xMax,10),yt=ticks(yMin,yMax,8);return <GraphFrame colors={colors}>{detail&&xt.map(x=><Line key={`x${x}`} x1={sx(x)} y1={PAD} x2={sx(x)} y2={H-PAD} stroke={colors.line}/>)}{detail&&yt.map(y=><Line key={`y${y}`} x1={PAD} y1={sy(y)} x2={W-PAD} y2={sy(y)} stroke={colors.line}/>)}<Line x1={Math.max(PAD,Math.min(W-PAD,sx(0)))} y1={PAD} x2={Math.max(PAD,Math.min(W-PAD,sx(0)))} y2={H-PAD} stroke={colors.ink} strokeWidth="2"/><Line x1={PAD} y1={Math.max(PAD,Math.min(H-PAD,sy(0)))} x2={W-PAD} y2={Math.max(PAD,Math.min(H-PAD,sy(0)))} stroke={colors.ink} strokeWidth="2"/>{segments.map((segment,index)=>segment.length>1?<Line key={index} x1={sx(segment[0].x)} y1={sy(segment[0].y)} x2={sx(segment[1].x)} y2={sy(segment[1].y)} stroke={accent} strokeWidth="3"/>:null)}{linePts.length>1&&<Line x1={sx(linePts[0].x)} y1={sy(linePts[0].y)} x2={sx(linePts[1].x)} y2={sy(linePts[1].y)} stroke={colors.info} strokeWidth="3" strokeDasharray="7 5"/>}{typeof data.queryX==='number'&&<Line x1={sx(data.queryX)} y1={PAD} x2={sx(data.queryX)} y2={H-PAD} stroke={colors.warning} strokeWidth="2" strokeDasharray="5 4"/>}{pts.map((point,index)=><G key={index} onPress={()=>setSelected(`${point.label||'Point'} (${point.x}, ${point.y})`)}><Circle cx={sx(point.x)} cy={sy(point.y)} r="8" fill={accent}/>{point.label&&<SvgText x={sx(point.x)+10} y={sy(point.y)-9} fontSize="12" fontWeight="700" fill={colors.ink}>{point.label}</SvgText>}</G>)}</GraphFrame>}

function Shape({data,colors,accent,detail}:{data:Row;colors:Colors;accent:string;detail:boolean}){const kind=label(data.kind);const common={fill:detail?`${accent}22`:'none',stroke:colors.ink,strokeWidth:3} as const;let drawing:React.ReactNode;if(kind==='circle'||kind==='wheel'||kind==='circle-theorem')drawing=<><Circle cx="210" cy="135" r="88" {...common}/>{kind!=='circle'&&Array.from({length:8},(_,i)=><Line key={i} x1="210" y1="135" x2={210+Math.cos(i*Math.PI/4)*88} y2={135+Math.sin(i*Math.PI/4)*88} stroke={colors.line} strokeWidth="2"/>)}</>;else if(kind==='rectangle'||kind==='rectangle-diagonal'||kind==='frame')drawing=<><Rect x="78" y="65" width="264" height="145" {...common}/>{kind==='rectangle-diagonal'&&<Line x1="78" y1="210" x2="342" y2="65" stroke={accent} strokeWidth="3"/>}{kind==='frame'&&<Rect x="125" y="100" width="170" height="75" fill={colors.raised} stroke={colors.ink} strokeWidth="2"/>}</>;else if(kind==='parallel-lines')drawing=<><Line x1="55" y1="78" x2="365" y2="78" stroke={colors.ink} strokeWidth="3"/><Line x1="55" y1="192" x2="365" y2="192" stroke={colors.ink} strokeWidth="3"/><Line x1="125" y1="235" x2="290" y2="35" stroke={accent} strokeWidth="3"/></>;else if(kind==='cuboid')drawing=<><Rect x="70" y="88" width="225" height="125" {...common}/><Path d="M70 88 L130 45 H355 V170 L295 213 M295 88 L355 45 M295 213 L355 170" fill="none" stroke={colors.ink} strokeWidth="3"/></>;else if(kind==='semicircle')drawing=<Path d="M75 205 A135 135 0 0 1 345 205 Z" {...common}/>;else drawing=<Polygon points={kind==='right-triangle'?'90,210 340,210 90,55':kind==='similar-triangles'?'45,210 160,210 85,100 220,210 385,210 280,55':'70,210 350,210 210,55'} {...common}/>;return <Svg width="100%" height="100%" viewBox={`0 0 ${W} ${H}`}>{drawing}{list(data.labels).map((value,index)=>{const item=row(value);return <SvgText key={index} x={number(item.x,210)} y={number(item.y,235)} textAnchor="middle" fontSize="14" fontWeight="700" fill={accent}>{label(item.text)}</SvgText>})}<SvgText x="400" y="257" textAnchor="end" fontSize="9" fill={colors.quiet}>not to scale</SvgText></Svg>}

function Pie({data,colors,accent}:{data:Row;colors:Colors;accent:string}){const angle=number(data.angle);const end=-Math.PI/2+angle*Math.PI/180,x=210+Math.cos(end)*90,y=130+Math.sin(end)*90;const path=angle?`M210 130 L210 40 A90 90 0 ${angle>180?1:0} 1 ${x} ${y} Z`:'';return <Svg width="100%" height="100%" viewBox={`0 0 ${W} ${H}`}><Circle cx="210" cy="130" r="90" fill={colors.muted} stroke={colors.ink} strokeWidth="3"/>{!!path&&<Path d={path} fill={accent} opacity=".7" stroke={colors.ink}/>}<SvgText x="210" y="248" textAnchor="middle" fill={colors.ink}>{angle?`${angle} deg sector`:label(data.prompt)}</SvgText></Svg>}
function NumberLine({data,colors,accent}:{data:Row;colors:Colors;accent:string}){const min=number(data.min,-5),max=number(data.max,5),lower=typeof data.lower==='number'?data.lower:undefined,upper=typeof data.upper==='number'?data.upper:undefined,sx=(value:number)=>45+(value-min)/(max-min||1)*330;return <Svg width="100%" height="100%" viewBox={`0 0 ${W} ${H}`}><Line x1="35" y1="135" x2="385" y2="135" stroke={colors.ink} strokeWidth="3"/>{ticks(min,max,12).map(value=><G key={value}><Line x1={sx(value)} y1="125" x2={sx(value)} y2="145" stroke={colors.ink}/><SvgText x={sx(value)} y="166" textAnchor="middle" fill={colors.quiet}>{value}</SvgText></G>)}<Line x1={sx(lower??min)} y1="135" x2={sx(upper??max)} y2="135" stroke={accent} strokeWidth="8"/>{lower!=null&&<Circle cx={sx(lower)} cy="135" r="9" fill={data.lowerClosed?accent:colors.raised} stroke={accent} strokeWidth="3"/>}{upper!=null&&<Circle cx={sx(upper)} cy="135" r="9" fill={data.upperClosed?accent:colors.raised} stroke={accent} strokeWidth="3"/>}</Svg>}
function Tally({data,colors,accent}:{data:Row;colors:Colors;accent:string}){const count=Math.max(0,Math.min(20,number(data.count)));return <Svg width="100%" height="100%" viewBox={`0 0 ${W} ${H}`}>{Array.from({length:count},(_,i)=>{const group=Math.floor(i/5),within=i%5,x=50+group*90+within*14;return within===4?<Line key={i} x1={42+group*90} y1="180" x2={94+group*90} y2="90" stroke={accent} strokeWidth="5"/>:<Line key={i} x1={x} y1="85" x2={x} y2="190" stroke={colors.ink} strokeWidth="5"/>})}</Svg>}
function Venn({data,colors,accent}:{data:Row;colors:Colors;accent:string}){const events=list(data.events).map(row);return <Svg width="100%" height="100%" viewBox={`0 0 ${W} ${H}`}>{events.map((item,index)=>{const cx=data.disjoint?130+index*160:175+index*70;return <G key={index}><Circle cx={cx} cy="130" r="76" fill={`${accent}22`} stroke={accent} strokeWidth="3"/><SvgText x={cx} y="120" textAnchor="middle" fontWeight="700" fill={colors.ink}>{label(item.label)}</SvgText><SvgText x={cx} y="148" textAnchor="middle" fill={colors.ink}>P = {label(item.value)}</SvgText></G>})}</Svg>}
function Tree({data,colors,accent}:{data:Row;colors:Colors;accent:string}){const stages=list(data.stages),first=list(stages[0]);return <Svg width="100%" height="100%" viewBox={`0 0 ${W} ${H}`}><Circle cx="45" cy="135" r="6" fill={accent}/>{first.map((value,index)=>{const y=75+index*120,secondRaw=list(stages[1]),second=Array.isArray(secondRaw[index])?list(secondRaw[index]):secondRaw;return <G key={index}><Line x1="45" y1="135" x2="185" y2={y} stroke={colors.ink} strokeWidth="2"/><SvgText x="112" y={(135+y)/2-5} fill={accent}>{label(value)}</SvgText>{second.map((next,nextIndex)=>{const endY=y-35+nextIndex*70;return <G key={nextIndex}><Line x1="185" y1={y} x2="370" y2={endY} stroke={colors.ink} strokeWidth="2"/><SvgText x="278" y={(y+endY)/2-5} fill={accent}>{label(next)}</SvgText></G>})}</G>})}</Svg>}
function DotPattern({data,colors,accent}:{data:Row;colors:Colors;accent:string}){const patterns=list(data.patterns).map(value=>number(value));return <Svg width="100%" height="100%" viewBox={`0 0 ${W} ${H}`}>{patterns.map((arm,index)=>{const cx=80+index*130,cy=125,dots:[[number,number]]=[[cx,cy]];for(let step=1;step<=arm;step++)dots.push([cx-step*17,cy],[cx+step*17,cy],[cx,cy-step*17],[cx,cy+step*17]);return <G key={index}>{dots.map(([x,y],dot)=><Circle key={dot} cx={x} cy={y} r="6" fill={accent}/>) }<SvgText x={cx} y="225" textAnchor="middle" fill={colors.ink}>Pattern {index+1}</SvgText></G>})}</Svg>}

function TableVisual({data,colors,accent,setSelected}:{data:Row;colors:Colors;accent:string;setSelected:(value:string)=>void}){const headings=list(data.headings),rows=list(data.rows).map(list);return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.table}><View>{headings.length>0&&<View style={styles.tableRow}>{headings.map((value,index)=><View key={index} style={[styles.cell,styles.headCell,{borderColor:colors.line,backgroundColor:colors.muted}]}><Text style={{color:colors.ink,fontWeight:'800'}}>{label(value)}</Text></View>)}</View>}{rows.map((cells,rowIndex)=><View key={rowIndex} style={styles.tableRow}>{cells.map((value,columnIndex)=><Pressable key={columnIndex} onPress={()=>setSelected(`${label(headings[columnIndex])||`Column ${columnIndex+1}`}: ${label(value)}`)} style={[styles.cell,{borderColor:colors.line,backgroundColor:columnIndex===0?colors.muted:colors.raised}]}><Text style={{color:columnIndex===0?accent:colors.ink,fontWeight:columnIndex===0?'800':'500'}}>{label(value)}</Text></Pressable>)}</View>)}</View></ScrollView>}
function BarVisual({data,colors,accent,detail,setSelected}:{data:Row;colors:Colors;accent:string;detail:boolean;setSelected:(value:string)=>void}){const values=list(data.data).map(row),max=Math.max(1,...values.map(item=>number(item.value)));return <View style={styles.bars}>{values.map((item,index)=>{const value=number(item.value),name=label(item.label)||`Item ${index+1}`;return <Pressable key={index} accessibilityLabel={`${name}, ${value}`} onPress={()=>setSelected(`${name}: ${value}`)} style={styles.barColumn}>{detail&&<Text style={{color:colors.ink,fontWeight:'800'}}>{value}</Text>}<View style={[styles.bar,{height:Math.max(14,value/max*145),backgroundColor:accent}]}/><Text numberOfLines={2} style={{color:colors.quiet,textAlign:'center',fontSize:11}}>{name}</Text></Pressable>})}</View>}
function CountersVisual({data,colors,setSelected}:{data:Row;colors:Colors;setSelected:(value:string)=>void}){return <View style={styles.groups}>{list(data.groups).map((value,index)=>{const item=row(value),count=Math.max(0,Math.min(30,number(item.count))),name=label(item.label)||`Group ${index+1}`,color=label(item.color)||colors.info;return <Pressable key={index} onPress={()=>setSelected(`${name}: ${count}`)} style={[styles.counterGroup,{borderColor:colors.line}]}><View style={styles.dots}>{Array.from({length:count},(_,dot)=><View key={dot} style={[styles.dot,{backgroundColor:color}]}/>)}</View><Text style={{color:colors.ink,fontWeight:'700'}}>{name}</Text></Pressable>})}</View>}
function DiceVisual({colors,accent,setSelected}:{colors:Colors;accent:string;setSelected:(value:string)=>void}){return <View style={styles.dice}>{[1,2,3,4,5,6].map(value=><Pressable key={value} onPress={()=>setSelected(`Die outcome: ${value}`)} style={[styles.die,{borderColor:colors.line,backgroundColor:colors.paper}]}><Text style={{fontSize:24,fontWeight:'900',color:accent}}>{value}</Text></Pressable>)}</View>}
function PictogramVisual({data,colors,accent}:{data:Row;colors:Colors;accent:string}){const count=Math.max(0,Math.min(40,number(data.count))),symbol=label(data.symbol)||'X';return <View style={styles.pictogram}><Text style={{color:colors.ink,fontWeight:'800'}}>Key: {symbol} = {label(data.value)}</Text><View style={styles.symbols}>{Array.from({length:count},(_,index)=><Text key={index} style={{color:accent,fontSize:24,fontWeight:'900'}}>{symbol}</Text>)}</View></View>}
function SampleSpaceVisual({data,colors,accent,setSelected}:{data:Row;colors:Colors;accent:string;setSelected:(value:string)=>void}){const size=Math.max(2,Math.min(8,number(data.size,6)));return <View style={styles.sample}>{Array.from({length:size},(_,r)=><View key={r} style={styles.sampleRow}>{Array.from({length:size},(_,c)=><Pressable key={c} onPress={()=>setSelected(`Outcome (${r+1}, ${c+1}), total ${r+c+2}`)} style={[styles.sampleCell,{borderColor:colors.line,backgroundColor:(r+c)%2?colors.raised:colors.muted}]}><Text style={{fontSize:10,color:accent,fontWeight:'700'}}>{r+1},{c+1}</Text></Pressable>)}</View>)}</View>}
function ProbabilityScale({colors,accent}:{colors:Colors;accent:string}){return <View style={styles.scale}><View style={[styles.scaleTrack,{backgroundColor:colors.line}]}><View style={[styles.scaleFill,{backgroundColor:accent}]}/></View><View style={styles.scaleLabels}><Text style={{color:colors.ink}}>0{`\n`}Impossible</Text><Text style={{color:colors.ink,textAlign:'center'}}>1/2{`\n`}Even chance</Text><Text style={{color:colors.ink,textAlign:'right'}}>1{`\n`}Certain</Text></View></View>}

const styles=StyleSheet.create({figure:{borderWidth:1,borderRadius:18,padding:12,gap:10,overflow:'hidden'},stage:{width:'100%',alignItems:'stretch',justifyContent:'center'},controls:{flexDirection:'row',justifyContent:'flex-end',gap:8,flexWrap:'wrap'},control:{minHeight:42,paddingHorizontal:12,borderWidth:1,borderRadius:12,flexDirection:'row',alignItems:'center',gap:7},readout:{minHeight:42,borderRadius:11,paddingHorizontal:12,paddingVertical:9,flexDirection:'row',alignItems:'center',gap:8},fallback:{minHeight:210,alignItems:'center',justifyContent:'center',gap:10,padding:20},table:{paddingVertical:12},tableRow:{flexDirection:'row'},cell:{width:125,minHeight:54,borderWidth:1,padding:9,justifyContent:'center'},headCell:{minHeight:62},bars:{height:210,flexDirection:'row',alignItems:'flex-end',justifyContent:'space-evenly',gap:6,paddingHorizontal:8},barColumn:{flex:1,height:200,alignItems:'center',justifyContent:'flex-end',gap:5},bar:{width:'72%',minWidth:18,borderTopLeftRadius:5,borderTopRightRadius:5},groups:{gap:10,padding:8},counterGroup:{borderWidth:1,borderRadius:14,padding:12,gap:8},dots:{flexDirection:'row',flexWrap:'wrap',gap:6},dot:{width:18,height:18,borderRadius:9},dice:{flexDirection:'row',flexWrap:'wrap',justifyContent:'center',gap:10},die:{width:68,height:68,borderWidth:1,borderRadius:15,alignItems:'center',justifyContent:'center'},pictogram:{gap:14,padding:12},symbols:{flexDirection:'row',flexWrap:'wrap',gap:8},sample:{alignSelf:'center'},sampleRow:{flexDirection:'row'},sampleCell:{width:38,height:38,borderWidth:1,alignItems:'center',justifyContent:'center'},scale:{padding:24,gap:13},scaleTrack:{height:10,borderRadius:5,overflow:'hidden'},scaleFill:{width:'50%',height:'100%'},scaleLabels:{flexDirection:'row',justifyContent:'space-between'}});
