"""Voiceover for the 25-second Reddit ad.

Synthesises the approved script line by line with Kokoro-82M (Apache-2.0)
using the British voice `bf_emma`, trims each line to its spoken span and
places it on the 25 s timeline at the onset listed in LINES. Writes:

  build/vo.wav        48 kHz mono voiceover stem, exactly 25.0 s
  build/vo.json       line + word timings on the global timeline
  src/vo-data.js      the same timings as `window.VO`, read by the animation

The caption track and the music ducking both read vo.json, so timings live
in one place. To swap in a human recording, replace build/vo.wav and keep
the onsets below (or re-time vo.json from the new take).
"""
import json
import sys
from pathlib import Path

import numpy as np
import soundfile as sf
from scipy.signal import resample_poly

ROOT = Path(__file__).resolve().parent.parent
BUILD = ROOT / "build"
DURATION = 25.0
SR_OUT = 48000
SR_TTS = 24000
VOICE = "bf_emma"
SPEED = 1.0

# (id, text exactly as spoken and captioned, onset of first word in seconds)
LINES = [
    ("L1", "Not sure what to revise next?", 0.35),
    ("L2", "GCSE Study Desk helps you find one useful next step.", 3.00),
    ("L3", "Choose Maths Foundation, Maths Higher, or English.", 7.40),
    ("L4", "Practise exam-style questions, see a worked method, and revisit mistakes as you learn.", 12.30),
    ("L5", "App and new features coming soon.", 20.95),
    ("L6", "Thanks for being here.", 23.20),
]

PRE_ROLL = 0.06   # keep a breath of room before the first phoneme
POST_ROLL = 0.18  # let the last word's tail ring out


def speech_bounds(audio, sr, threshold_db=-42.0, win=0.01):
    """First and last sample where the smoothed level clears the threshold."""
    n = max(1, int(sr * win))
    power = np.convolve(audio.astype(np.float64) ** 2, np.ones(n) / n, mode="same")
    level = 10 * np.log10(power + 1e-12)
    loud = np.flatnonzero(level > threshold_db)
    return loud[0] / sr, loud[-1] / sr


def main():
    from kokoro import KPipeline

    BUILD.mkdir(exist_ok=True)
    pipe = KPipeline(lang_code="b", repo_id="hexgrad/Kokoro-82M")
    track = np.zeros(int(DURATION * SR_OUT), dtype=np.float32)
    out_lines = []

    for line_id, text, onset in LINES:
        chunks = list(pipe(text, voice=VOICE, speed=SPEED))
        if len(chunks) != 1:
            sys.exit(f"{line_id}: expected one chunk, got {len(chunks)}")
        res = chunks[0]
        audio = res.audio.numpy() if hasattr(res.audio, "numpy") else np.asarray(res.audio)
        start_s, end_s = speech_bounds(audio, SR_TTS)
        a0 = max(0.0, start_s - PRE_ROLL)
        a1 = min(len(audio) / SR_TTS, end_s + POST_ROLL)
        clip = audio[int(a0 * SR_TTS):int(a1 * SR_TTS)].astype(np.float32)
        fade_in, fade_out = int(0.008 * SR_TTS), int(0.06 * SR_TTS)
        clip[:fade_in] *= np.linspace(0, 1, fade_in)
        clip[-fade_out:] *= np.linspace(1, 0, fade_out) ** 2
        clip48 = resample_poly(clip, SR_OUT, SR_TTS).astype(np.float32)

        # Global placement: the first audible phoneme lands on `onset`.
        shift = onset - start_s  # TTS-local time -> global time
        place = a0 + shift
        i0 = int(round(place * SR_OUT))
        i1 = i0 + len(clip48)
        if i0 < 0 or i1 > len(track):
            sys.exit(f"{line_id}: clip {place:.2f}-{i1 / SR_OUT:.2f}s falls outside the timeline")
        track[i0:i1] += clip48

        words = []
        for tok in res.tokens or []:
            if tok.start_ts is None or not any(ch.isalnum() for ch in tok.text):
                continue
            words.append({
                "text": tok.text,
                "start": round(tok.start_ts + shift, 3),
                "end": round(tok.end_ts + shift, 3),
            })
        # Kokoro word ends include trailing pause; clamp the last one to audible speech.
        speech_end = end_s + shift
        if words:
            words[-1]["end"] = round(min(words[-1]["end"], speech_end + 0.05), 3)
            words[0]["start"] = round(max(words[0]["start"], onset - 0.02), 3)
        out_lines.append({
            "id": line_id,
            "text": text,
            "start": round(onset, 3),
            "end": round(speech_end, 3),
            "phonemes": res.phonemes,
            "words": words,
        })
        print(f"{line_id} {onset:6.2f} -> {speech_end:6.2f}s  {text}")

    peak = float(np.max(np.abs(track)))
    track *= 0.89 / peak  # about -1 dBFS; loudness is set in the mix
    sf.write(BUILD / "vo.wav", track, SR_OUT, subtype="FLOAT")
    data = json.dumps({
        "voice": VOICE,
        "speed": SPEED,
        "engine": "Kokoro-82M (hexgrad/Kokoro-82M, Apache-2.0)",
        "duration": DURATION,
        "lines": out_lines,
    }, indent=2)
    (BUILD / "vo.json").write_text(data)
    (ROOT / "src" / "vo-data.js").write_text(
        "// Generated by scripts/tts.py. Do not edit by hand.\nwindow.VO = " + data + ";\n")

    gaps = [(b["start"] - a["end"]) for a, b in zip(out_lines, out_lines[1:])]
    print("gaps between lines:", [round(g, 2) for g in gaps])
    print("tail after last word:", round(DURATION - out_lines[-1]["end"], 2), "s")


if __name__ == "__main__":
    main()
