/**
 * Topic registry for the Learning section.
 * notes: [{t:'p',text} | {t:'b',items:[..]} | {t:'f',title,text} | {t:'e',q,a}]
 * resources: [{label, url, why}]
 */
export const STRANDS = {
  number: {
    id: 'number',
    name: 'Number',
    blurb: 'Calculations, place value, fractions, decimals & percentages.',
    weight: 25,
    color: '#7c5cff',
  },
  algebra: {
    id: 'algebra',
    name: 'Algebra',
    blurb: 'Expressions, equations, sequences & graphs.',
    weight: 20,
    color: '#ff5c8a',
  },
  ratio: {
    id: 'ratio',
    name: 'Ratio & Proportion',
    blurb: 'Sharing, scaling, best buy & maps.',
    weight: 25,
    color: '#ffb020',
  },
  geometry: {
    id: 'geometry',
    name: 'Geometry & Measures',
    blurb: 'Angles, shapes, Pythagoras, trigonometry & transformations.',
    weight: 15,
    color: '#2ad4a8',
  },
  probability: {
    id: 'probability',
    name: 'Probability',
    blurb: 'Chance, fractions, trees & expectation.',
    weight: 7.5,
    color: '#35a7ff',
  },
  statistics: {
    id: 'statistics',
    name: 'Statistics',
    blurb: 'Averages, charts & scatter graphs.',
    weight: 7.5,
    color: '#ff7849',
  },
};

const RES = {
  corbett: (q) => ({
    label: 'Corbettmaths',
    url: `https://corbettmaths.com/?s=${encodeURIComponent(q)}`,
    why: 'Free videos, textbooks & practice questions.',
  }),
  mathsgenie: {
    label: 'Maths Genie',
    url: 'https://www.mathsgenie.co.uk/gcse-revision.html',
    why: 'Free revision notes, exam questions & video solutions.',
  },
  bbc: (q) => ({
    label: 'BBC Bitesize',
    url: 'https://www.bbc.co.uk/bitesize/subjects/z38pycw',
    why: 'Bitesize guides with step-by-step examples.',
  }),
  khan: {
    label: 'Khan Academy',
    url: 'https://www.khanacademy.org/math',
    why: 'Free interactive lessons & unlimited practice.',
  },
};

const F = (title, text) => ({ t: 'f', title, text });
const P = (text) => ({ t: 'p', text });
const B = (items) => ({ t: 'b', items });
const E = (q, a) => ({ t: 'e', q, a });

export const TOPICS = [
  {
    id: 'place-value',
    strand: 'number',
    name: 'Place Value & Ordering',
    blurb: 'Big numbers, decimals, negatives & ordering.',
    examWeight: 6,
    notes: [
      P('The value of a digit depends on its position. In 4729 the 7 is worth 700 (hundreds).'),
      B([
        'Ascending = smallest to largest, descending = largest to smallest.',
        'Negative numbers: the further left, the smaller. −12 < −7.',
        'When ordering decimals line up the decimal points first.',
        'To round, look one digit to the right: 5 or more rounds up, 4 or less stays.',
        'Significant figures: count from the first non-zero digit.',
      ]),
      F('Rounding rule', '5 or more → round up.  4 or less → round down.'),
      E('Round 3867 to the nearest hundred', 'Look at the tens digit (6): it is 5 or more, so round up → 3900.'),
    ],
    resources: [RES.corbett('place value'), RES.mathsgenie, RES.bbc('place value'), RES.khan],
  },
  {
    id: 'operations',
    strand: 'number',
    name: 'Four Operations & BIDMAS',
    blurb: 'Long multiplication, division & order of operations.',
    examWeight: 6,
    notes: [
      P('Always use BIDMAS: Brackets, Indices, Division/Multiplication (left to right), Addition/Subtraction (left to right).'),
      B([
        'Division and multiplication have equal priority — work left to right.',
        'For long multiplication, split into parts or use the grid method.',
        'Check answers with estimation: round the numbers first.',
        'Multiplying by 100 moves every digit two places left; dividing moves it right.',
      ]),
      F('BIDMAS', 'Brackets → Indices → Division/Multiplication → Addition/Subtraction'),
      E('Work out 3 + 4 × 5', 'Multiplication comes before addition: 3 + (4 × 5) = 3 + 20 = 23.'),
    ],
    resources: [RES.corbett('multiplication'), RES.mathsgenie, RES.bbc('order of operations'), RES.khan],
  },
  {
    id: 'fractions',
    strand: 'number',
    name: 'Fractions',
    blurb: 'Equivalent fractions, four rules & mixed numbers.',
    examWeight: 6,
    notes: [
      P('A fraction is a division: 3/4 means 3 ÷ 4. The top is the numerator, the bottom is the denominator.'),
      B([
        'To add or subtract, make the denominators the same first (LCM).',
        'To multiply: multiply tops, multiply bottoms, then simplify.',
        'To divide: keep the first, flip the second, multiply (KFC).',
        'To simplify: divide top and bottom by the same number.',
        'To find a fraction of an amount: divide by the bottom, multiply by the top.',
      ]),
      F('Four rules', 'a/b + c/d = (ad + cb)/bd   ·   a/b × c/d = ac/bd   ·   a/b ÷ c/d = a/b × d/c'),
      E('Work out 3/4 of 28', '28 ÷ 4 = 7, then 7 × 3 = 21.'),
    ],
    resources: [RES.corbett('fractions'), RES.mathsgenie, RES.bbc('fractions'), RES.khan],
  },
  {
    id: 'decimals',
    strand: 'number',
    name: 'Decimals',
    blurb: 'Adding, subtracting, multiplying & dividing decimals.',
    examWeight: 4,
    notes: [
      B([
        'Line up decimal points when adding or subtracting.',
        'Multiplying decimals: multiply as whole numbers, then put the decimal point back — total decimal places in the answer = total in the question.',
        'Dividing by a decimal: multiply both numbers by 10, 100… until you divide by a whole number.',
        '0.3 × 0.4 = 0.12 (2 decimal places in the question → 2 in the answer).',
      ]),
      F('Decimal shift', '× 10 → move point right 1   ·   ÷ 10 → move point left 1'),
      E('4.6 × 3', '46 × 3 = 138. One decimal place in the question → 13.8.'),
    ],
    resources: [RES.corbett('decimals'), RES.mathsgenie, RES.bbc('decimals'), RES.khan],
  },
  {
    id: 'percentages',
    strand: 'number',
    name: 'Percentages',
    blurb: 'Percentage of amounts, increase & decrease.',
    examWeight: 6,
    notes: [
      P('Percent means "out of 100". 50% = 1/2, 25% = 1/4, 10% = 1/10.'),
      B([
        'Find 10% by dividing by 10 — then build any percentage from 1%, 10%, 50%.',
        'Increase by 20% → multiply by 1.20.  Decrease by 20% → multiply by 0.80.',
        'To reverse a percentage, divide by the multiplier: ÷ 1.20 undoes +20%.',
        '"What percentage is A of B?" → A ÷ B × 100.',
      ]),
      F('Multipliers', '+15% → ×1.15   ·   −15% → ×0.85   ·   reverse +15% → ÷1.15'),
      E('A £40 hoodie has 25% off. New price?', '25% of 40 = 10. 40 − 10 = £30. (Or 40 × 0.75 = 30.)'),
    ],
    resources: [RES.corbett('percentages'), RES.mathsgenie, RES.bbc('percentages'), RES.khan],
  },
  {
    id: 'money-finance',
    strand: 'number',
    name: 'Money & Finance',
    blurb: 'Tax, budgeting, bills & best deals — big marks in your exam.',
    examWeight: 6,
    notes: [
      P('AQA loves "financial mathematics": you will need to add, subtract, multiply and use percentages on real money problems.'),
      B([
        'Tax (UK income tax): the first £12,570 you earn is tax-free; you pay 20% on the rest (up to £50,270).',
        'Always write money in pounds with 2 decimal places, e.g. £23.40.',
        'Change from £20 = £20 − cost.',
        'To find a price that is bad or good value, work out the price per unit first.',
      ]),
      F('Tax rule', 'Tax = 20% of (income − £12,570)'),
      E('You earn £20,000 a year. Tax?', '20,000 − 12,570 = 7,430 taxed. 20% of 7,430 = £1,486.'),
    ],
    resources: [RES.corbett('money'), RES.mathsgenie, RES.bbc('financial mathematics'), RES.khan],
  },
  {
    id: 'expressions',
    strand: 'algebra',
    name: 'Expressions & Simplifying',
    blurb: 'Collecting terms, expanding & factorising.',
    examWeight: 7,
    notes: [
      B([
        'Only "like terms" combine: 3x + 4x = 7x, but x and x² are different.',
        'Expanding: multiply the outside term by everything inside: 3(x + 2) = 3x + 6.',
        'Factorising is expanding backwards: 3x + 6 = 3(x + 2).',
        'x × x = x², x² × x³ = x⁵ (add powers), x⁵ ÷ x² = x³ (subtract powers).',
      ]),
      F('Index laws', 'aᵐ × aⁿ = aᵐ⁺ⁿ   ·   aᵐ ÷ aⁿ = aᵐ⁻ⁿ'),
      E('Simplify 5a + 3b − 2a + b', '5a − 2a = 3a and 3b + b = 4b → 3a + 4b.'),
    ],
    resources: [RES.corbett('algebraic expressions'), RES.mathsgenie, RES.bbc('algebraic expressions'), RES.khan],
  },
  {
    id: 'equations',
    strand: 'algebra',
    name: 'Solving Equations',
    blurb: 'One-step to two-sided equations.',
    examWeight: 7,
    notes: [
      P('Solve equations by doing the same thing to BOTH sides — the equation is a balance.'),
      B([
        'Get x-terms on one side and numbers on the other.',
        'Undo + with −, × with ÷, in reverse order of BIDMAS.',
        'With brackets: expand first, then solve.',
        'Check by substituting your answer back in.',
      ]),
      F('Golden rule', 'Do the same to both sides'),
      E('Solve 3x + 4 = 19', '3x = 19 − 4 = 15 → x = 15 ÷ 3 = 5. Check: 3×5+4 = 19 ✓'),
    ],
    resources: [RES.corbett('equations'), RES.mathsgenie, RES.bbc('solving equations'), RES.khan],
  },
  {
    id: 'sequences',
    strand: 'algebra',
    name: 'Sequences',
    blurb: 'Term-to-term rules & nth term.',
    examWeight: 4,
    notes: [
      B([
        'A term-to-term rule says how to get the next term, e.g. "add 3".',
        'The nth term of an arithmetic sequence is dn + (first term − d).',
        'Common difference d = difference between consecutive terms.',
        'To find the 20th term, substitute n = 20.',
        'To find which term equals a number, solve nth term = that number.',
      ]),
      F('nth term', 'nth term = dn + (a − d)   ·   e.g. 3, 7, 11… → 4n − 1'),
      E('nth term of 3, 7, 11, 15…', 'd = 4, a = 3 → 4n + (3 − 4) = 4n − 1.'),
    ],
    resources: [RES.corbett('sequences'), RES.mathsgenie, RES.bbc('sequences'), RES.khan],
  },
  {
    id: 'inequalities',
    strand: 'algebra',
    name: 'Inequalities',
    blurb: 'Solving & showing inequalities.',
    examWeight: 4,
    notes: [
      B([
        '> greater than   ·   < less than   ·   ≥ greater than or equal to   ·   ≤ less than or equal to.',
        'Solve them like equations, but reverse the inequality sign when multiplying or dividing by a negative number.',
        'Open circle ○ for < and >, filled circle ● for ≤ and ≥ on a number line.',
        '"x is at most 7" means x ≤ 7. "x is at least 7" means x ≥ 7.',
      ]),
      F('Key words', 'at most → ≤   ·   at least → ≥   ·   more than → >   ·   fewer than → <'),
      E('Solve 2x − 1 ≤ 9', '2x ≤ 10 → x ≤ 5.'),
    ],
    resources: [RES.corbett('inequalities'), RES.mathsgenie, RES.bbc('inequalities'), RES.khan],
  },
  {
    id: 'formulae',
    strand: 'algebra',
    name: 'Formulae & Substitution',
    blurb: 'Plugging numbers into formulae & changing the subject.',
    examWeight: 4,
    notes: [
      B([
        'Substitution: replace letters with numbers, then use BIDMAS. Use brackets for negatives: 3x with x = −2 → 3 × (−2).',
        'Speed = distance ÷ time   ·   Density = mass ÷ volume   ·   Pressure = force ÷ area.',
        'To change the subject, undo operations in reverse order.',
        '°C to °F: Fahrenheit = (9/5 × °C) + 32.',
      ]),
      F('Key formulae', 'Speed = D/T   ·   Density = M/V   ·   Pressure = F/A'),
      E('v = u + at. u = 4, a = 2, t = 3', 'v = 4 + (2 × 3) = 10.'),
    ],
    resources: [RES.corbett('substitution'), RES.mathsgenie, RES.bbc('substitution'), RES.khan],
  },
  {
    id: 'graphs',
    strand: 'algebra',
    name: 'Straight Line Graphs',
    blurb: 'y = mx + c, gradients & intercepts.',
    examWeight: 4,
    notes: [
      B([
        'y = mx + c: m is the gradient (steepness), c is the y-intercept (where it crosses the y-axis).',
        'Gradient = change in y ÷ change in x (rise over run).',
        'Parallel lines have the same gradient.',
        'To check if a point is on a line, substitute its coordinates.',
        'Horizontal lines: y = 3. Vertical lines: x = −2.',
      ]),
      F('Line equation', 'y = mx + c   ·   gradient m = (y₂ − y₁) ÷ (x₂ − x₁)'),
      E('Gradient through (1,3) and (5,11)', 'm = (11 − 3) ÷ (5 − 1) = 8 ÷ 4 = 2.'),
    ],
    resources: [RES.corbett('y mx c'), RES.mathsgenie, RES.bbc('straight line graphs'), RES.khan],
  },
  {
    id: 'ratio',
    strand: 'ratio',
    name: 'Ratio & Sharing',
    blurb: 'Simplifying ratios and sharing amounts.',
    examWeight: 8,
    notes: [
      P('A ratio compares parts of a whole. 3 : 5 means 8 parts in total.'),
      B([
        'Simplify like a fraction: divide all parts by the HCF.',
        'To share £72 in the ratio 3 : 5: 8 parts → £9 per part → £27 and £45.',
        'To find a fraction from a ratio: 3 : 5 → 5/8 of the total is the second part.',
        'If you know one part, scale up using the ratio.',
      ]),
      F('Ratio method', 'Total parts = parts added · amount per part = total ÷ parts'),
      E('Share £72 in the ratio 3 : 5', '8 parts → £72 ÷ 8 = £9/part → 3×9 = £27 and 5×9 = £45.'),
    ],
    resources: [RES.corbett('ratio'), RES.mathsgenie, RES.bbc('ratio'), RES.khan],
  },
  {
    id: 'proportion',
    strand: 'ratio',
    name: 'Proportion & Best Buy',
    blurb: 'Recipes, exchange rates & value for money.',
    examWeight: 8,
    notes: [
      B([
        'Direct proportion: as one thing doubles, the other doubles.',
        'Recipes: multiply every ingredient by the same scale factor.',
        'Best buy: work out the price per unit (e.g. pence per 100 g) for both and compare.',
        'Exchange rate: "£1 = $1.25" → to buy $, multiply by 1.25; to convert back, divide.',
        'Profit = selling price − cost. Loss = cost − selling price.',
      ]),
      F('Proportion', 'Unit rate → scale up · £ ↔ $ via the exchange rate'),
      E('A recipe for 4 needs 200 g flour. How much for 10?', 'Scale factor 10 ÷ 4 = 2.5 → 200 × 2.5 = 500 g.'),
    ],
    resources: [RES.corbett('proportion'), RES.mathsgenie, RES.bbc('direct proportion'), RES.khan],
  },
  {
    id: 'scale',
    strand: 'ratio',
    name: 'Scale & Maps',
    blurb: 'Map scales, enlargements & similar shapes.',
    examWeight: 6,
    notes: [
      B([
        'A scale of 1 : 25000 means 1 cm on the map = 25,000 cm (250 m) in real life.',
        'Map to real life: multiply. Real life to map: divide.',
        'Always convert: 1 km = 1000 m = 100,000 cm.',
        'Enlargement by scale factor 3 multiplies every length by 3.',
        'Bearings are always 3 digits, measured clockwise from North.',
      ]),
      F('Scale', 'Real = map × scale   ·   map = real ÷ scale'),
      E('Map 1 : 25000, road is 4 cm. Real length?', '4 × 25,000 = 100,000 cm = 1,000 m = 1 km.'),
    ],
    resources: [RES.corbett('map scales'), RES.mathsgenie, RES.bbc('scale'), RES.khan],
  },
  {
    id: 'angles',
    strand: 'geometry',
    name: 'Angles & Parallel Lines',
    blurb: 'Triangles, polygons and angle rules.',
    examWeight: 5,
    notes: [
      B([
        'Angles on a straight line add to 180°. Angles around a point add to 360°.',
        'Triangle = 180°. Quadrilateral = 360°.',
        'Alternate angles are equal. Corresponding angles are equal.',
        'Co-interior angles add to 180°.',
        'Interior angle of a regular n-gon: 180 × (n − 2) ÷ n. Exterior angles add to 360°.',
        'Vertically opposite angles are equal.',
      ]),
      F('Key sums', 'Line 180° · Point 360° · Triangle 180° · n-gon 180(n − 2)°'),
      E('Two angles on a straight line: one is 128°. Find the other.', '180 − 128 = 52°.'),
    ],
    resources: [RES.corbett('angles'), RES.mathsgenie, RES.bbc('angles'), RES.khan],
  },
  {
    id: 'area-perimeter',
    strand: 'geometry',
    name: 'Area & Perimeter',
    blurb: 'Rectangles, triangles, trapeziums & compound shapes.',
    examWeight: 5,
    notes: [
      B([
        'Rectangle: area = base × height, perimeter = add all sides.',
        'Triangle: area = 1/2 × base × height (height is perpendicular to base).',
        'Parallelogram: area = base × height.',
        'Trapezium: area = 1/2 × (a + b) × height.',
        'Compound shapes: split into rectangles/triangles, work them out, add (or subtract).',
        'Units: area is cm²/m², perimeter is cm/m.',
      ]),
      F('Area formulae', 'Triangle ½bh · Parallelogram bh · Trapezium ½(a+b)h · Rectangle bh'),
      E('Triangle with base 8 cm, height 5 cm', 'Area = 1/2 × 8 × 5 = 20 cm².'),
    ],
    resources: [RES.corbett('area of shapes'), RES.mathsgenie, RES.bbc('area'), RES.khan],
  },
  {
    id: 'circles',
    strand: 'geometry',
    name: 'Circles',
    blurb: 'Circumference & area with π.',
    examWeight: 4,
    notes: [
      B([
        'Radius r = half the diameter. d = 2r.',
        'Circumference = π × d = 2πr.',
        'Area = π × r².',
        'Use π = 3.14 unless told otherwise (or the calculator button).',
        'A semicircle is half a circle — remember to add the diameter for its perimeter.',
        '"Give your answer in terms of π" — leave the π in, e.g. 12π.',
      ]),
      F('Circle formulae', 'C = πd   ·   A = πr²'),
      E('Circle radius 4 cm. Area?', 'A = π × 4² = 16π ≈ 16 × 3.14 = 50.24 cm².'),
    ],
    resources: [RES.corbett('area of a circle'), RES.mathsgenie, RES.bbc('circles'), RES.khan],
  },
  {
    id: 'volume-surface',
    strand: 'geometry',
    name: 'Volume & Surface Area',
    blurb: 'Cuboids, cubes & prisms.',
    examWeight: 4,
    notes: [
      B([
        'Volume = area of cross-section × length (works for every prism).',
        'Cuboid volume = length × width × height.',
        'Surface area = add the area of every face.',
        '1 cm³ = 1 ml, 1000 cm³ = 1 litre.',
        'A cube has 6 identical square faces.',
      ]),
      F('Volume', 'Cuboid: V = lwh   ·   Prism: V = cross-section × length'),
      E('Box 5 cm × 4 cm × 3 cm. Volume?', '5 × 4 × 3 = 60 cm³.'),
    ],
    resources: [RES.corbett('volume'), RES.mathsgenie, RES.bbc('volume'), RES.khan],
  },
  {
    id: 'pythagoras',
    strand: 'geometry',
    name: 'Pythagoras',
    blurb: 'Right-angled triangles: a² + b² = c².',
    examWeight: 4,
    notes: [
      B([
        'Only works in RIGHT-ANGLED triangles.',
        'c is always the hypotenuse (longest side, opposite the right angle).',
        'To find the hypotenuse: c = √(a² + b²).',
        'To find a shorter side: a = √(c² − b²).',
        'Recognise 3-4-5, 5-12-13, 8-15-17 triples — they appear everywhere.',
      ]),
      F('Pythagoras', 'a² + b² = c²'),
      E('Sides 9 cm and 12 cm. Hypotenuse?', 'c² = 9² + 12² = 81 + 144 = 225 → c = 15 cm.'),
    ],
    resources: [RES.corbett('pythagoras'), RES.mathsgenie, RES.bbc('pythagoras'), RES.khan],
  },
  {
    id: 'trigonometry',
    strand: 'geometry',
    name: 'Trigonometry',
    blurb: 'SOHCAHTOA for right-angled triangles.',
    examWeight: 4,
    notes: [
      P('With an angle in a right-angled triangle, label the sides: O = opposite the angle, A = next to the angle, H = hypotenuse.'),
      B([
        'Sin θ = O/H   ·   Cos θ = A/H   ·   Tan θ = O/A.',
        'Know your special angles: sin 30° = 1/2, cos 60° = 1/2, tan 45° = 1.',
        'Finding a side: choose the correct ratio, substitute the known values, then rearrange for the unknown side.',
        'Finding an angle: use the inverse button on your calculator (sin⁻¹).',
      ]),
      F('SOH CAH TOA', 'sin = O/H · cos = A/H · tan = O/A'),
      E('H = 10 cm, angle 30°. Find the opposite side.', 'O = H × sin 30° = 10 × 1/2 = 5 cm.'),
    ],
    resources: [RES.corbett('trigonometry'), RES.mathsgenie, RES.bbc('trigonometry'), RES.khan],
  },
  {
    id: 'transformations',
    strand: 'geometry',
    name: 'Transformations & Symmetry',
    blurb: 'Translation, reflection, rotation & enlargement.',
    examWeight: 4,
    notes: [
      B([
        'Translation: described by a vector (x on top, y below, e.g. (3, −2) = right 3, down 2).',
        'Reflection: every point is the same distance from the mirror line; in the x-axis the y changes sign, in the y-axis the x changes sign.',
        'Rotation: 90° clockwise, 180° etc. about a centre. Half a turn reverses both signs.',
        'Enlargement by scale factor k about the origin: multiply both coordinates by k.',
        'Lines of symmetry and order of rotational symmetry describe shapes.',
      ]),
      F('Transformations', 'Reflect in y-axis: (x, y) → (−x, y)   ·   Enlarge by k: (x, y) → (kx, ky)'),
      E('Reflect (4, 2) in the y-axis', 'x changes sign → (−4, 2).'),
    ],
    resources: [RES.corbett('transformations'), RES.mathsgenie, RES.bbc('transformations'), RES.khan],
  },
  {
    id: 'probability-basic',
    strand: 'probability',
    name: 'Basic Probability',
    blurb: 'The probability scale & single events.',
    examWeight: 4,
    notes: [
      P('Probability measures how likely something is: 0 = impossible, 1 = certain. Everything else is between.'),
      B([
        'P(event) = number of ways it can happen ÷ total outcomes.',
        'All probabilities for one event add up to 1.',
        'P(not A) = 1 − P(A).',
        'Expected number of times = probability × number of trials.',
        'Give answers as fractions in their simplest form.',
      ]),
      F('Probability', 'P(win) + P(lose) = 1   ·   Expected = P × trials'),
      E('Bag: 3 red, 7 blue. P(red)?', '3 out of 10 → 3/10. P(not red) = 1 − 3/10 = 7/10.'),
    ],
    resources: [RES.corbett('probability'), RES.mathsgenie, RES.bbc('probability'), RES.khan],
  },
  {
    id: 'probability-combined',
    strand: 'probability',
    name: 'Combined Probability',
    blurb: 'Two events, sample spaces & tree diagrams.',
    examWeight: 4,
    notes: [
      B([
        'For two independent events, multiply their probabilities.',
        'Sample space diagrams list all outcomes (e.g. two dice = 36 outcomes).',
        'Tree diagrams: multiply along branches, add between them.',
        'Events are mutually exclusive if they cannot both happen — add their probabilities.',
      ]),
      F('AND / OR rule', 'AND → multiply · OR (mutually exclusive) → add'),
      E('Two coins tossed. P(both heads)?', 'P(H) × P(H) = 1/2 × 1/2 = 1/4.'),
    ],
    resources: [RES.corbett('sample space'), RES.mathsgenie, RES.bbc('probability'), RES.khan],
  },
  {
    id: 'averages',
    strand: 'statistics',
    name: 'Averages & Range',
    blurb: 'Mean, median, mode & range.',
    examWeight: 5,
    notes: [
      B([
        'Mean = sum of all values ÷ how many there are.',
        'Median = middle value when ordered (mean of the two middle values if even count).',
        'Mode = most common value. Range = biggest − smallest.',
        'From a frequency table: mean = Σ(fx) ÷ Σf; median position = (n+1)/2.',
        'Outliers (extreme values) push the mean around — median is more robust.',
      ]),
      F('Mean', 'Mean = total ÷ count   ·   Range = max − min'),
      E('Scores: 4, 7, 9, 12. Mean?', '(4+7+9+12) ÷ 4 = 32 ÷ 4 = 8.'),
    ],
    resources: [RES.corbett('averages'), RES.mathsgenie, RES.bbc('averages'), RES.khan],
  },
  {
    id: 'charts',
    strand: 'statistics',
    name: 'Charts & Diagrams',
    blurb: 'Pie charts, bar charts & two-way tables.',
    examWeight: 4,
    notes: [
      B([
        'Pie chart: each item = its fraction × 360°. Total angles = 360°.',
        'To read a pie chart: angle ÷ 360 × total.',
        'Bar charts: height = frequency, bars are equal width with gaps.',
        'Two-way tables: read off the row and column your item sits at.',
        'Pictograms & frequency tables: check the key before reading.',
      ]),
      F('Pie charts', 'Angle = (value ÷ total) × 360°'),
      E('90 students, 45 say "yes". Pie angle?', '45/90 = 1/2 → 1/2 × 360 = 180°.'),
    ],
    resources: [RES.corbett('pie charts'), RES.mathsgenie, RES.bbc('charts'), RES.khan],
  },
  {
    id: 'scatter',
    strand: 'statistics',
    name: 'Scatter Graphs',
    blurb: 'Correlation & lines of best fit.',
    examWeight: 4,
    notes: [
      B([
        'Positive correlation: as one value rises, the other rises.',
        'Negative correlation: as one rises, the other falls.',
        'No correlation: no pattern.',
        'A line of best fit goes through the middle of the points (roughly equal each side).',
        'Use the line of best fit to ESTIMATE values, NOT the points themselves.',
        'An outlier is a point far from the pattern.',
      ]),
      F('Correlation', 'Up together → positive · Up/down → negative · Scattered → none'),
      E('Plot age vs height, points rising to the right', 'Positive correlation.'),
    ],
    resources: [RES.corbett('scatter graphs'), RES.mathsgenie, RES.bbc('scatter graphs'), RES.khan],
  },
];
