// Renders the social adverts in design/social/: four 1080×1350 (4:5) PNGs
// for Instagram and Reddit. The posts live in scripts/social/posts.jsx and
// are drawn with the real Circuit components (emblems, level tiles, scenes,
// Pip and a live explainer frame), so they can't drift from the product.
// Counts come from the content sources and the URL from the landing page's
// canonical link, so a rebuild keeps every claim in sync.
// Run: npm run social:build            (all posts)
//      npm run social:build -- map     (one post, by id)
// Set CHROMIUM_PATH if Playwright's own Chromium is not installed,
// SOCIAL_URL to print a different address in the footer, and
// SOCIAL_SCALE=2 for 2160×2700 files (same layout, twice the pixels).
import { build } from 'esbuild';
import { chromium } from '@playwright/test';
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const OUT = path.join(root, 'design/social');
const WIDTH = 1080;
const HEIGHT = 1350;
const SCALE = Number(process.env.SOCIAL_SCALE || 1);
if (![1, 2, 3].includes(SCALE)) throw new Error('SOCIAL_SCALE must be 1, 2 or 3.');
const ORIGIN = 'http://social.local';

// ---------- Facts (never hand-typed on a post) ----------
const { loadBank, bankSize } = await import(pathToFileURL(path.join(root, 'server/src/subjects/maths/bank/index.js')).href);
const { loadHigherBank, higherBankSize, higherTopics } = await import(pathToFileURL(path.join(root, 'server/src/subjects/maths/bank/higher.js')).href);
const { TOPICS } = await import(pathToFileURL(path.join(root, 'server/src/subjects/maths/bank/topics.js')).href);
const { MATHS_EXPLAINERS } = await import(pathToFileURL(path.join(root, 'clients/shared/explainer/library/maths/index.js')).href);
const { ENGLISH_EXPLAINERS } = await import(pathToFileURL(path.join(root, 'clients/shared/explainer/library/english/index.js')).href);
await loadBank();
await loadHigherBank();

const covers = (ids) => (script) => script.topics.some((topic) => ids.has(topic));
const foundationIds = new Set(TOPICS.map((topic) => topic.id));
const higherIds = new Set(higherTopics().map((topic) => topic.id));
const canonical = readFileSync(path.join(root, 'selector/index.html'), 'utf8').match(/<link rel="canonical" href="([^"]+)"/)?.[1];
const url = (process.env.SOCIAL_URL || canonical || '').replace(/^https?:\/\//, '').replace(/\/$/, '');
if (!url) throw new Error('No public URL: add a canonical link to selector/index.html or set SOCIAL_URL.');

const facts = {
  url,
  questions: { foundation: bankSize(), higher: higherBankSize() },
  explainers: {
    foundation: MATHS_EXPLAINERS.filter(covers(foundationIds)).length,
    higher: MATHS_EXPLAINERS.filter(covers(higherIds)).length,
    english: ENGLISH_EXPLAINERS.length,
  },
};

// ---------- Page ----------
const buildDir = path.join(root, 'scripts/social/.build');
mkdirSync(buildDir, { recursive: true });
const bundle = path.join(buildDir, 'social.js');
const shared = { bundle: true, jsx: 'automatic', logLevel: 'error' };
await build({
  ...shared,
  entryPoints: [path.join(root, 'scripts/social/client.jsx')],
  platform: 'browser',
  format: 'iife',
  define: { 'process.env.NODE_ENV': '"production"' },
  outfile: bundle,
});
// A Node copy of the posts module, read for ids, file names and alt text.
const meta = path.join(buildDir, 'posts.mjs');
await build({ ...shared, entryPoints: [path.join(root, 'scripts/social/posts.jsx')], platform: 'node', format: 'esm', packages: 'external', outfile: meta });
const { POSTS } = await import(pathToFileURL(meta).href);

// Fonts as the public site ships them (generated by npm run art:export).
const fontFaces = readFileSync(path.join(root, 'selector/circuit-public.css'), 'utf8').match(/@font-face \{[^}]+\}/g).join('\n');
const CIRCUIT = ['tokens', 'base', 'video', 'learn', 'home', 'pages'];
const html = `<!doctype html>
<html lang="en-GB" data-theme="light">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=${WIDTH}" />
<style>${fontFaces}</style>
${CIRCUIT.map((name) => `<link rel="stylesheet" href="/circuit/${name}.css" />`).join('\n')}
<link rel="stylesheet" href="/social.css" />
<script>window.__FACTS__ = ${JSON.stringify(facts)};</script>
</head>
<body>
<div id="root"></div>
<script src="/social.js"></script>
</body>
</html>`;

const files = {
  '/': { body: html, contentType: 'text/html' },
  '/social.css': { path: path.join(root, 'scripts/social/social.css'), contentType: 'text/css' },
  '/social.js': { path: bundle, contentType: 'text/javascript' },
};
for (const name of CIRCUIT) files[`/circuit/${name}.css`] = { path: path.join(root, `clients/shared/circuit/${name}.css`), contentType: 'text/css' };

// ---------- Capture ----------
const wanted = process.argv.slice(2);
const posts = POSTS.filter((post) => !wanted.length || wanted.includes(post.id));
if (!posts.length) throw new Error(`No post matches ${wanted.join(', ')}. Ids: ${POSTS.map((post) => post.id).join(', ')}`);
mkdirSync(OUT, { recursive: true });

const browser = await chromium.launch(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {});
const context = await browser.newContext({ viewport: { width: WIDTH, height: HEIGHT }, deviceScaleFactor: SCALE, reducedMotion: 'reduce' });
await context.route(`${ORIGIN}/**`, async (route) => {
  const { pathname } = new URL(route.request().url());
  if (pathname.startsWith('/fonts/')) {
    return route.fulfill({ path: path.join(root, 'selector/fonts', path.basename(pathname)), contentType: 'font/woff2' });
  }
  const file = files[pathname];
  if (!file) return route.fulfill({ status: 404, body: 'Not found' });
  return route.fulfill(file.path ? { path: file.path, contentType: file.contentType } : { body: file.body, contentType: file.contentType });
});

const page = await context.newPage();
const problems = [];
page.on('pageerror', (error) => problems.push(error.message));
page.on('console', (message) => { if (message.type() === 'error') problems.push(message.text()); });
for (const post of posts) {
  await page.goto(`${ORIGIN}/?post=${encodeURIComponent(post.id)}`);
  await page.waitForFunction(() => document.body.dataset.ready || document.body.dataset.error, null, { timeout: 20000 });
  const error = await page.evaluate(() => document.body.dataset.error);
  if (error) throw new Error(`Post "${post.id}" failed to render:\n${error}`);
  // Nothing may sit in the outer 40px (feeds crop and round the edges),
  // except art marked data-bleed. data-layer marks full-canvas wrappers.
  // Text is measured by its glyph runs, because nowrap text can overflow
  // the box that holds it.
  const outside = await page.evaluate(({ w, h, safe }) => {
    const out = (box) => box.width && box.height && (box.left < safe || box.top < safe || box.right > w - safe || box.bottom > h - safe);
    const where = (box) => `[${Math.round(box.left)},${Math.round(box.top)} → ${Math.round(box.right)},${Math.round(box.bottom)}]`;
    const kept = (el) => !el.closest('[data-bleed]');
    const boxes = [...document.querySelectorAll('.post *')]
      .filter((el) => kept(el) && !el.hasAttribute('data-layer'))
      .map((el) => ({ box: el.getBoundingClientRect(), name: `${el.tagName.toLowerCase()}.${String(el.className?.baseVal ?? el.className).trim().split(/\s+/).join('.')}` }));
    const walker = document.createTreeWalker(document.querySelector('.post'), NodeFilter.SHOW_TEXT);
    const range = document.createRange();
    for (let node = walker.nextNode(); node; node = walker.nextNode()) {
      if (!node.textContent.trim() || !kept(node.parentElement)) continue;
      range.selectNodeContents(node);
      boxes.push({ box: range.getBoundingClientRect(), name: `text “${node.textContent.trim().slice(0, 24)}”` });
    }
    return boxes.filter(({ box }) => out(box)).map(({ box, name }) => `${name} ${where(box)}`);
  }, { w: WIDTH, h: HEIGHT, safe: 40 });
  if (outside.length) problems.push(`${post.id}: ${outside.length} element(s) outside the safe area, e.g. ${outside.slice(0, 3).join('; ')}`);
  const file = path.join(OUT, `${post.file}.png`);
  await page.screenshot({ path: file, type: 'png' });
  console.log(`Wrote design/social/${post.file}.png (${WIDTH * SCALE}×${HEIGHT * SCALE})`);
}
await browser.close();
rmSync(buildDir, { recursive: true, force: true });
// A full build owns the folder's PNGs and alt text: drop any PNG left by
// a renamed post.
if (!wanted.length) {
  const alt = POSTS.map((post) => `## ${post.file}.png\n\n${post.alt(facts)}\n`).join('\n');
  writeFileSync(path.join(OUT, 'alt-text.md'), `<!-- GENERATED by npm run social:build from scripts/social/posts.jsx. Do not edit by hand. -->\n# Alt text\n\nPaste each description into the image's alt-text field on Instagram or Reddit.\n\n${alt}`);
  console.log('Wrote design/social/alt-text.md');
  const current = new Set(POSTS.map((post) => `${post.file}.png`));
  for (const name of readdirSync(OUT).filter((file) => file.endsWith('.png') && !current.has(file))) {
    rmSync(path.join(OUT, name));
    console.log(`Removed stale design/social/${name}`);
  }
}
console.log(`Facts: ${JSON.stringify(facts)}`);
if (problems.length) {
  console.error(`\n${problems.length} problem(s):\n- ${problems.join('\n- ')}`);
  process.exitCode = 1;
}
