// Renders the Circuit React graphics to static SVG strings for the public
// pages in selector/ (which ship without React). Output: selector/art.js,
// which fills every <span data-art="name"></span> placeholder at load.
// Re-run after changing any graphic in clients/shared/circuit/.
import { build } from 'esbuild';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
// Build next to the project so bare imports (react, react-dom) resolve
// from website/node_modules; packages stay external (no bundling of CJS).
const dir = path.join(root, 'scripts/art/.build');
mkdirSync(dir, { recursive: true });
const outfile = path.join(dir, 'art.mjs');
await build({
  entryPoints: [path.join(root, 'scripts/art/entry.jsx')],
  bundle: true,
  platform: 'node',
  format: 'esm',
  jsx: 'automatic',
  packages: 'external',
  outfile,
  logLevel: 'error',
});
const { ART } = await import(pathToFileURL(outfile).href);
rmSync(dir, { recursive: true, force: true });

const banner = `// GENERATED by scripts/export-art.mjs — do not edit by hand.
// Static Circuit graphics for the dependency-free public pages. Each
// <span data-art="name"></span> is replaced with the matching inline SVG,
// so colours follow the page's CSS variables and the light/dark theme.
`;
const body = `(() => {
  const ART = ${JSON.stringify(ART)};
  for (const slot of document.querySelectorAll('[data-art]')) {
    const markup = ART[slot.getAttribute('data-art')];
    if (markup) slot.innerHTML = markup;
  }
})();
`;
writeFileSync(path.join(root, 'selector/art.js'), banner + body);
console.log(`Wrote selector/art.js with ${Object.keys(ART).length} graphics (${Math.round((banner + body).length / 1024)} KB).`);

// Public stylesheet: vendored @font-face + the shared tokens + the graphics
// primitives/motion section of base.css (between @public markers).
const FONT_FACES = `@font-face { font-family: 'Unbounded Variable'; font-style: normal; font-display: swap; font-weight: 200 900; src: url(/fonts/unbounded-latin-wght-normal.woff2) format('woff2-variations'); }
@font-face { font-family: 'Atkinson Hyperlegible Next Variable'; font-style: normal; font-display: swap; font-weight: 200 800; src: url(/fonts/atkinson-hyperlegible-next-latin-wght-normal.woff2) format('woff2-variations'); }
@font-face { font-family: 'Atkinson Hyperlegible Next Variable'; font-style: italic; font-display: swap; font-weight: 200 800; src: url(/fonts/atkinson-hyperlegible-next-latin-wght-italic.woff2) format('woff2-variations'); }
@font-face { font-family: 'Atkinson Hyperlegible Mono Variable'; font-style: normal; font-display: swap; font-weight: 200 800; src: url(/fonts/atkinson-hyperlegible-mono-latin-wght-normal.woff2) format('woff2-variations'); }
@font-face { font-family: 'Literata Variable'; font-style: normal; font-display: swap; font-weight: 200 900; src: url(/fonts/literata-latin-wght-normal.woff2) format('woff2-variations'); }
@font-face { font-family: 'Literata Variable'; font-style: italic; font-display: swap; font-weight: 200 900; src: url(/fonts/literata-latin-wght-italic.woff2) format('woff2-variations'); }
@font-face { font-family: 'Kalam'; font-style: normal; font-display: swap; font-weight: 400; src: url(/fonts/kalam-latin-400-normal.woff2) format('woff2'); }
@font-face { font-family: 'Kalam'; font-style: normal; font-display: swap; font-weight: 700; src: url(/fonts/kalam-latin-700-normal.woff2) format('woff2'); }
`;
const tokens = readFileSync(path.join(root, 'clients/shared/circuit/tokens.css'), 'utf8');
const base = readFileSync(path.join(root, 'clients/shared/circuit/base.css'), 'utf8');
const start = base.indexOf('/* @public:start');
const end = base.indexOf('/* @public:end */');
if (start < 0 || end < 0) throw new Error('base.css is missing the @public markers');
const publicCss = `/* GENERATED by scripts/export-art.mjs — do not edit by hand.
   Circuit tokens + graphics for the public pages (selector/). Edit
   clients/shared/circuit/tokens.css or base.css, then npm run art:export. */
${FONT_FACES}
${tokens}
${base.slice(start, end)}`;
writeFileSync(path.join(root, 'selector/circuit-public.css'), publicCss);
console.log(`Wrote selector/circuit-public.css (${Math.round(publicCss.length / 1024)} KB).`);
