import { Link } from 'expo-router';
import { forwardRef, type PropsWithChildren } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View, type PressableProps, type ScrollViewProps, type TextInputProps, type ViewProps } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNetwork, usePreferences } from './providers';
import { recommendation, subjectTokens, useTheme } from './theme';

export function Screen({children,style,...props}:ViewProps){const {colors}=useTheme();return <SafeAreaView style={[styles.screen,{backgroundColor:colors.paper},style]} {...props}><PaperPattern/>{children}</SafeAreaView>}
export function ScrollScreen({children,...props}:ScrollViewProps){const {colors}=useTheme();return <SafeAreaView style={[styles.screen,{backgroundColor:colors.paper}]}><PaperPattern/><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" {...props}>{children}</ScrollView></SafeAreaView>}
export function PaperPattern(){const {colors}=useTheme();return <View pointerEvents="none" accessible={false} accessibilityElementsHidden importantForAccessibility="no-hide-descendants" style={StyleSheet.absoluteFill}>{Array.from({length:30},(_,i)=><View key={i} style={{position:'absolute',top:i*24,left:0,right:0,borderTopWidth:StyleSheet.hairlineWidth,borderColor:colors.line,opacity:.35}}/> )}</View>}
export function DeskHeader({title,eyebrow}: {title:string;eyebrow?:string}){const {colors,subject}=useTheme();return <View style={[styles.header,{borderBottomColor:colors.ink}]}><Text style={[styles.meta,{color:subject.accent}]}>{eyebrow??subject.label}</Text><Text accessibilityRole="header" style={[styles.h1,{color:colors.ink}]}>{title}</Text></View>}
export function Button({children,variant='primary',...props}:PressableProps&PropsWithChildren&{variant?:'primary'|'secondary'|'danger'}){const {colors,subject}=useTheme();const bg=variant==='primary'?subject.accent:variant==='danger'?colors.negative:colors.raised;const fg=variant==='secondary'?colors.ink:'#fff';return <Pressable accessibilityRole="button" style={({pressed})=>[styles.button,{backgroundColor:bg,borderColor:variant==='secondary'?colors.strong:bg,opacity:pressed?.75:props.disabled?.55:1}]} {...props}><Text style={[styles.buttonText,{color:fg}]}>{children}</Text></Pressable>}
export const Field=forwardRef<TextInput,TextInputProps&{label:string}>(({label,...props},ref)=>{const {colors}=useTheme();return <View style={styles.field}><Text style={[styles.meta,{color:colors.quiet}]}>{label}</Text><TextInput ref={ref} accessibilityLabel={label} placeholderTextColor={colors.quiet} style={[styles.input,{color:colors.ink,backgroundColor:colors.raised,borderColor:colors.strong}]} {...props}/></View>});Field.displayName='Field';
export function Notice({kind='empty',title,children}:PropsWithChildren&{kind?:'loading'|'error'|'offline'|'empty'|'success';title:string}){const {colors}=useTheme();const color=kind==='error'?colors.negative:kind==='success'?colors.positive:kind==='offline'?colors.warning:colors.info;return <View accessibilityRole={kind==='error'?'alert':undefined} style={[styles.notice,{borderColor:color,backgroundColor:colors.raised}]}>{kind==='loading'&&<ActivityIndicator color={color}/>}<Text style={[styles.meta,{color}]}>{title}</Text>{children&&<Text style={{color:colors.ink,lineHeight:21}}>{children}</Text>}</View>}
export function SectionHeader({title,meta}: {title:string;meta?:string}){const {colors}=useTheme();return <View style={[styles.row,{borderBottomColor:colors.ink}]}><Text accessibilityRole="header" style={[styles.h2,{color:colors.ink}]}>{title}</Text>{meta&&<Text style={[styles.meta,{color:colors.quiet}]}>{meta}</Text>}</View>}
export function PaperDocket({paper,title,detail}: {paper:string;title:string;detail:string}){const {colors,subject}=useTheme();return <View style={[styles.docket,{backgroundColor:colors.raised,borderColor:colors.strong,borderLeftColor:subject.accent}]}><Text style={[styles.meta,{color:subject.accent}]}>{paper}</Text><Text style={[styles.h2,{color:colors.ink}]}>{title}</Text><Text style={{color:colors.quiet}}>{detail}</Text></View>}
export function NextSessionCard(){const {subject}=usePreferences();return <PaperDocket paper="NEXT SESSION" title={subjectTokens[subject].label} detail={recommendation(subject)}/>}
export function ProgressMeter({value,label}: {value:number;label:string}){const {colors,subject}=useTheme();const safe=Math.max(0,Math.min(1,value));return <View accessibilityRole="progressbar" accessibilityValue={{min:0,max:100,now:Math.round(safe*100)}}><Text style={[styles.meta,{color:colors.quiet}]}>{label}</Text><View style={{height:8,backgroundColor:colors.muted,marginTop:8}}><View style={{width:`${safe*100}%`,height:8,backgroundColor:subject.accent}}/></View></View>}
export function ExpertiseSeal({grade}: {grade:string}){const {colors,subject}=useTheme();return <View accessibilityLabel={`Working grade ${grade}`} style={[styles.seal,{borderColor:subject.accent}]}><Text style={[styles.meta,{color:colors.quiet}]}>WORKING GRADE</Text><Text style={[styles.h2,{color:subject.accent}]}>{grade}</Text></View>}
export function PressableRow({title,detail,href}: {title:string;detail?:string;href:string}){const {colors}=useTheme();return <Link href={href as never} asChild><Pressable accessibilityRole="link" style={[styles.pressRow,{borderBottomColor:colors.line}]}><View style={{flex:1}}><Text style={{color:colors.ink,fontSize:17,fontWeight:'700'}}>{title}</Text>{detail&&<Text style={{color:colors.quiet,marginTop:3}}>{detail}</Text>}</View><Text style={{color:colors.quiet,fontSize:20}}>›</Text></Pressable></Link>}
export function Skeleton({width='100%',height=18}: {width?:number|`${number}%`;height?:number}){const {colors}=useTheme();return <View accessibilityLabel="Loading" style={{width,height,backgroundColor:colors.muted,marginVertical:5}}/>}
export function OfflineBanner(){const {online}=useNetwork();return online?null:<Notice kind="offline" title="OFFLINE">Data already held in this app session may remain available. Reconnect before starting new work.</Notice>}
export function Placeholder({title,eyebrow,children}:PropsWithChildren&{title:string;eyebrow:string}){return <ScrollScreen><DeskHeader title={title} eyebrow={eyebrow}/><OfflineBanner/>{children??<Notice title="HANDOFF READY">This route and its shared foundation are ready for the feature implementation.</Notice>}</ScrollScreen>}
const styles=StyleSheet.create({screen:{flex:1},content:{padding:20,paddingBottom:48,gap:18},header:{paddingVertical:18,borderBottomWidth:1,gap:5},h1:{fontFamily:'serif',fontSize:40,lineHeight:48,letterSpacing:-1.2},h2:{fontFamily:'serif',fontSize:25},meta:{fontFamily:'monospace',fontSize:11,fontWeight:'700',letterSpacing:1,textTransform:'uppercase'},button:{minHeight:48,paddingHorizontal:18,paddingVertical:12,justifyContent:'center',alignItems:'center',borderWidth:1},buttonText:{fontSize:15,fontWeight:'800',textAlign:'center',flexShrink:1},field:{gap:7},input:{minHeight:48,borderWidth:1,paddingHorizontal:12,paddingVertical:12,fontSize:16},notice:{borderWidth:1,padding:14,gap:8},row:{minHeight:48,flexDirection:'row',flexWrap:'wrap',alignItems:'center',justifyContent:'space-between',gap:8,borderBottomWidth:1},docket:{borderWidth:1,borderLeftWidth:6,padding:18,gap:8},seal:{minWidth:112,minHeight:112,padding:10,borderWidth:2,alignItems:'center',justifyContent:'center',gap:5},pressRow:{minHeight:56,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12,borderBottomWidth:1,paddingVertical:10}});
