// Generated by scripts/tts.py. Do not edit by hand.
window.VO = {
  "voice": "bf_emma",
  "speed": 1.0,
  "engine": "Kokoro-82M (hexgrad/Kokoro-82M, Apache-2.0)",
  "duration": 25.0,
  "lines": [
    {
      "id": "L1",
      "text": "Not sure what to revise next?",
      "start": 0.35,
      "end": 2.072,
      "phonemes": "n\u02cc\u0252t \u0283\u02c8\u028a\u0259 w\u02cc\u0252t t\u0259 \u0279\u026av\u02c8Iz n\u02c8\u025bkst?",
      "words": [
        {
          "text": "Not",
          "start": 0.362,
          "end": 0.6
        },
        {
          "text": "sure",
          "start": 0.6,
          "end": 0.862
        },
        {
          "text": "what",
          "start": 0.862,
          "end": 1.062
        },
        {
          "text": "to",
          "start": 1.062,
          "end": 1.162
        },
        {
          "text": "revise",
          "start": 1.162,
          "end": 1.587
        },
        {
          "text": "next",
          "start": 1.587,
          "end": 2.122
        }
      ]
    },
    {
      "id": "L2",
      "text": "GCSE Study Desk helps you find one useful next step.",
      "start": 3.0,
      "end": 6.464,
      "phonemes": "\u02a4\u02cci\u02d0s\u02cci\u02d0\u02cc\u025bs\u02c8i\u02d0 st\u02c8\u028cdi d\u02c8\u025bsk h\u02c8\u025blps ju\u02d0 f\u02c8Ind w\u02c8\u028cn j\u02c8u\u02d0sf\u028al n\u02c8\u025bkst st\u02c8\u025bp.",
      "words": [
        {
          "text": "GCSE",
          "start": 2.989,
          "end": 3.664
        },
        {
          "text": "Study",
          "start": 3.664,
          "end": 3.989
        },
        {
          "text": "Desk",
          "start": 3.989,
          "end": 4.477
        },
        {
          "text": "helps",
          "start": 4.477,
          "end": 4.777
        },
        {
          "text": "you",
          "start": 4.777,
          "end": 4.889
        },
        {
          "text": "find",
          "start": 4.889,
          "end": 5.164
        },
        {
          "text": "one",
          "start": 5.164,
          "end": 5.389
        },
        {
          "text": "useful",
          "start": 5.389,
          "end": 5.789
        },
        {
          "text": "next",
          "start": 5.789,
          "end": 6.064
        },
        {
          "text": "step",
          "start": 6.064,
          "end": 6.514
        }
      ]
    },
    {
      "id": "L3",
      "text": "Choose Maths Foundation, Maths Higher, or English.",
      "start": 7.4,
      "end": 10.058,
      "phonemes": "\u02a7\u02c8u\u02d0z m\u02c8a\u03b8s fWnd\u02c8A\u0283\u1d4an, m\u02c8a\u03b8s h\u02c8I\u0259, \u0254\u02d0 \u02c8\u026a\u014b\u0261l\u026a\u0283.",
      "words": [
        {
          "text": "Choose",
          "start": 7.38,
          "end": 7.652
        },
        {
          "text": "Maths",
          "start": 7.652,
          "end": 7.977
        },
        {
          "text": "Foundation",
          "start": 7.977,
          "end": 8.677
        },
        {
          "text": "Maths",
          "start": 8.752,
          "end": 9.077
        },
        {
          "text": "Higher",
          "start": 9.077,
          "end": 9.377
        },
        {
          "text": "or",
          "start": 9.427,
          "end": 9.552
        },
        {
          "text": "English",
          "start": 9.552,
          "end": 10.108
        }
      ]
    },
    {
      "id": "L4",
      "text": "Practise exam-style questions, see a worked method, and revisit mistakes as you learn.",
      "start": 12.3,
      "end": 16.78,
      "phonemes": "p\u0279\u02c8akt\u026as \u026a\u0261z\u02ccamst\u02c8Il kw\u02c8\u025bs\u02a7\u1d4anz, s\u02c8i\u02d0 \u0250 w\u02c8\u025c\u02d0kt m\u02c8\u025b\u03b8\u0259d, and \u0279\u02cci\u02d0v\u02c8\u026az\u026at m\u026ast\u02c8Aks az ju\u02d0 l\u02c8\u025c\u02d0n.",
      "words": [
        {
          "text": "Practise",
          "start": 12.28,
          "end": 12.64
        },
        {
          "text": "exam-style",
          "start": 12.64,
          "end": 13.29
        },
        {
          "text": "questions",
          "start": 13.29,
          "end": 14.09
        },
        {
          "text": "see",
          "start": 14.202,
          "end": 14.352
        },
        {
          "text": "a",
          "start": 14.352,
          "end": 14.415
        },
        {
          "text": "worked",
          "start": 14.415,
          "end": 14.715
        },
        {
          "text": "method",
          "start": 14.715,
          "end": 15.115
        },
        {
          "text": "and",
          "start": 15.152,
          "end": 15.265
        },
        {
          "text": "revisit",
          "start": 15.265,
          "end": 15.652
        },
        {
          "text": "mistakes",
          "start": 15.652,
          "end": 16.152
        },
        {
          "text": "as",
          "start": 16.152,
          "end": 16.265
        },
        {
          "text": "you",
          "start": 16.265,
          "end": 16.39
        },
        {
          "text": "learn",
          "start": 16.39,
          "end": 16.83
        }
      ]
    },
    {
      "id": "L5",
      "text": "App and new features coming soon.",
      "start": 20.95,
      "end": 22.779,
      "phonemes": "\u02c8ap and nj\u02c8u\u02d0 f\u02c8i\u02d0\u02a7\u0259z k\u02c8\u028cm\u026a\u014b s\u02c8u\u02d0n.",
      "words": [
        {
          "text": "App",
          "start": 20.95,
          "end": 21.225
        },
        {
          "text": "and",
          "start": 21.225,
          "end": 21.35
        },
        {
          "text": "new",
          "start": 21.35,
          "end": 21.563
        },
        {
          "text": "features",
          "start": 21.563,
          "end": 22.0
        },
        {
          "text": "coming",
          "start": 22.0,
          "end": 22.338
        },
        {
          "text": "soon",
          "start": 22.338,
          "end": 22.829
        }
      ]
    },
    {
      "id": "L6",
      "text": "Thanks for being here.",
      "start": 23.2,
      "end": 24.314,
      "phonemes": "\u03b8\u02c8a\u014bks f\u0254\u02d0 b\u02c8i\u02d0\u026a\u014b h\u02c8\u026a\u0259.",
      "words": [
        {
          "text": "Thanks",
          "start": 23.18,
          "end": 23.495
        },
        {
          "text": "for",
          "start": 23.495,
          "end": 23.62
        },
        {
          "text": "being",
          "start": 23.62,
          "end": 23.92
        },
        {
          "text": "here",
          "start": 23.92,
          "end": 24.364
        }
      ]
    }
  ]
};
