/**
 * Exemplar model answers for each extended question, used for:
 * - offline mode (self-marking against a banded rubric)
 * - the "show me a model answer" flow after AI marking
 * Illustrative responses, not examiner-validated marks or grade benchmarks.
 */
import { P1_MODELS } from './p1-exemplars.js';

const MODEL = {
  ...P1_MODELS,
  'p1-great-expectations': {
    q2: 'The writer piles up verbs and adjectives to make the stranger seem barely human. The noun phrase "a fearful man, all in coarse grey" immediately places him outside normal society, while the list of participles — "soaked", "smothered", "lamed", "cut", "stung", "torn" — overwhelms the reader with what he has suffered. The verbs "limped", "shivered", "glared" and "growled" pair animal sounds with human shape, and the detail that his teeth "chattered in his head" makes his fear audible. Dickens ends with the man "seizing" Pip by the chin: the violent physical contact is sudden, and the reader feels as trapped as Pip.',
    q3: 'The extract opens with a long, brooding description of the marshes, establishing loneliness before any action happens. Dickens then shifts abruptly into dialogue — "Hold your noise!" — a violent interruption that mirrors Pip\u2019s shock. The middle of the text is a single extended description of the convict, piling clause on clause so that the reader, like Pip, cannot look away. Structurally, the writer widens fear outward at the end: the man is not alone, "there\u2019s a young man hid with me", and the threat extends into the future ("will softly creep and creep") — so the extract ends on suspense, forcing us to read on.',
    q4: 'I strongly agree with the statement. The convict provokes terror — "I\u2019ll cut your throat" and the threat to "tear him open" are genuinely disturbing — but Dickens deliberately balances the horror with pity. The list of his injuries ("lamed by stones", "torn by briars") shows us a man broken by suffering, and details like his chattering teeth reveal fear beneath the aggression. His methodical threats even whisper vulnerability; he is out on the marsh, starving, "all in coarse grey", hunted. The writer makes us see the convict as Pip sees him — a monster who is also a victim — and this double impression is what makes the passage so memorable.',
    q5plan: 'Option: description of a threatening place.\n\nPara 1 — Zoom in on ONE detail (a gate, a light, a sound). Start with a short, blunt sentence for tension.\nPara 2 — The senses: what can be heard (wind through a fence, a dog far off), smelled (damp earth), felt (cold on the face).\nPara 3 — Shift to what is MISSING — the silence, the absence of people — and how that absence presses in.\nPara 4 — A hint of movement; something not quite seen. End on a sentence that holds the sense of dread.\n\nThroughout: metaphors (the dark "leaning in"), personification of the landscape, varied sentence lengths for pace.',
  },
  'p1-war-of-the-worlds': {
    q2: 'Wells makes the Martian horrifying by pairing precise anatomical nouns — "brow ridges", "wedge-like lower lip", "tentacles" — with adjectives that undermine them: "peculiar", "incessant", "tumultuous". The assonance and emphasis of "vital, intense, inhuman, crippled and monstrous" builds a rhythm of disgust, climaxing in the one-word judgement "monstrous". The simile-like phrase "something fungoid in the oily brown skin" links the creature to decay and disease, and the narrator\u2019s direct confession — "overcome with disgust and dread" — licenses the reader\u2019s own revulsion, turning observation into horror.',
    q3: 'Wells telescopes his structure from the cosmic to the physical. The opening paragraph establishes a god-like overview of the whole earth, then "yet" pivots the reader toward the enemy, and finally the extract drops to a single roadside encounter: one man, one machine, one "disgust and dread". This narrowing focus — universe, enemy, creature, man — mirrors a lens zooming in, and the tension rises as the scale shrinks. The closing image of the cylinder "rising slowly and painfully" is left unresolved, deliberately structuring the ending as a hook rather than a conclusion.',
    q4: 'I agree that the contrast is the extract\u2019s engine. Humanity is presented with ironic grandeur — "infinite complacency", "serene in their assurance of their empire over matter" — a confidence the reader already knows is about to be destroyed, which creates dramatic irony. Against this self-satisfaction, the Martians are "vast and cool and unsympathetic", their calm a mirror of ours but superior in scale. The physical description then deflates us further: we are examined like "creatures in a drop of water". The writer makes the invasion terrifying precisely because the one thing humanity is sure of — its own importance — is the illusion the text dismantles, sentence by sentence.',
    q5plan: 'Option: story about a discovery that changes everything.\n\nPara 1 — Establish normal life with one vivid, ordinary detail (a breakfast, a walk, a chore).\nPara 2 — The discovery begins small: an object, a sound, a mark. Misdirect the reader slightly.\nPara 3 — Reveal the truth gradually through the character\u2019s reactions; let dialogue carry the shock.\nPara 4 — Consequences start to ripple — what changes first? End on a question or a threatening image.\n\nThroughout: contrast calm and alarm, use short sentences for shock inside longer descriptive ones.',
  },
  'p1-jane-eyre': {
    q2: 'Brontë\u2019s language makes the red-room both luxurious and prison-like. The repetition of "red" — red damask, crimson cloth, the red carpet — saturates the room with the colour of danger and blood, while "chill", "silent" and "solemn" build an air of ritual and death. The simile comparing the bed to "a tabernacle" is almost religious, making the room a place of judgement rather than rest. Yet the description is also claustrophobic: the windows are "shrouded" and "blinds always drawn down", cutting off light and escape. Even the white bed, "like a pale throne", suggests power, not comfort — a place where an accused child is displayed, not slept.',
    q3: 'The extract is structured as a physical and emotional descent. It begins outside with the cold garden and the word that sets the tone, "chill", then moves inside, deeper and deeper — from the sitting-room, to the window seat, and finally to the red-room itself, the house\u2019s heart of secrets. The sentences grow temporarily longer and more ornamental as Brontë inventories the furniture, slowing time the way a frightened child experiences it. The writer saves the triple judgement — "chill... silent... solemn" — for the end, so the extract closes by sealing Jane in, and the structure itself becomes the trap.',
    q4: 'I agree that loneliness and powerlessness are the extract\u2019s core feelings. Jane is excluded by the weather, by the family ("Mrs. Reed... dined early"), and by her body, which she is taught is "inferior". Brontë keeps her almost voiceless — the entire passage is her watching, never her speaking. The house offers hiding places, but they only deepen her solitude: the window seat withdraws her from the family, and the red-room is where she will literally be locked in. The writer links powerlessness to space itself: every room Jane enters belongs to someone else. The passage persuades us not through argument but by making us feel the architecture of a childhood without welcome.',
    q5plan: 'Option: description of a room with a strange atmosphere.\n\nPara 1 — Name the room in a single sentence and note what it is used for (or that it is never used).\nPara 2 — Colour and light: describe what enters and what is kept out.\nPara 3 — Texture and memory: objects that hold stories; a smell, a layer of dust.\nPara 4 — The room\u2019s effect on the person inside; end with what it makes them feel.\n\nThroughout: personify the room ("the room waited"), layer sensory detail rather than listing it.',
  },
  'p1-treasure-island': {
    q2: 'Stevenson assembles the captain from ragged, tactile details: "tarry pigtail", "soiled blue coat", "hands ragged and scarred, with black, broken nails". These compound noun phrases do double work — each one gives the reader a picture AND a judgement. The simile hidden in "a bit of stick like a handspike" quietly makes him seem half-sailor, half-weapon, and even his singing is described as a "high, old tottering voice... tuned and broken at the capstan bars", as if the ship has worn grooves into the man himself. The word "scathed"? Nothing is pretty; every verb he performs — plodding, rapping, glaring — is heavy and threatening, so that danger arrives before he says a word.',
    q3: 'Stevenson structures the extract as a series of arrivals, each one darker than the last. It opens with the memorable framing "I remember him as if it were yesterday", which plants the extract in memory and signals that what follows matters. The arrival at the door is comic — the song, the rum, the toast to the "sittyated grog-shop" — but the writer then folds in the sinister: the payment for watching for a one-legged man, and the narrator\u2019s "thousand diabolical" dreams. The final paragraph converts comedy into routine menace — "the fierce routine of his habits" — and the ending image of the captain "glaring into the dark" leaves the reader unsettled and curious.',
    q4: 'I agree that the captain balances comedy and terror. Comedy flows from exaggeration — the deafening rum-drinking, the enormous sunburned face, the pretence of manners ("Much company, mate?") — yet Stevenson undercuts every laugh with threat: the song erupts from the same mouth that shouts for rum, and the boy who is paid a "silver fourpenny" is being groomed to watch for a man the captain clearly fears. The dreams of the one-legged seafarer turn the payment sour. By alternating joviality with menace so smoothly, the writer creates a character we can neither trust nor ignore — the longest-lasting kind of villain.',
    q5plan: 'Option: story about a secret a child is paid to keep.\n\nPara 1 — The transaction: who, what, how much. Make the bribe small and specific.\nPara 2 — The child\u2019s attempts to act normally, and the details they begin to notice around them.\nPara 3 — A test: something almost happens; the secret nearly surfaces. Quicken the pace.\nPara 4 — A resolution where the child must choose; end on the moment of decision or its cost.\n\nThroughout: first-person voice, concrete coins/details, short sentences under pressure.',
  },
  'p1-dracula': {
    q2: 'Stoker builds fear through sound before anything is seen. The wolves\u2019 howl is first "a sound so faint at first that it might have been the wind in the pines" — the simile delays the threat, and the oxymoron "sorrowful and cruel" makes the noise feel unnatural. His physical response — "my blood seemed to freeze in my veins" — transfers the fear into the body. The blue flames, "as though the night itself were lighting little lamps", are described as beautiful before the driver explains they mark graves, so beauty converts abruptly into dread. Throughout, the similes (the carriage "rocking like a ship on a stormy sea") keep the landscape unstable, and the final metaphor of the castle as "a crouching beast" turns architecture into predator.',
    q3: 'Stoker structures the extract as one long increase in pressure, measured in stages: unease at dusk, the first howl, the wolves\u2019 chorus, the ghost-lights, and finally the castle. Each stage is introduced by a specific marker of time ("As the evening fell...", "Then, far off in the darkness...", "Suddenly..."), which acts like a drumbeat counting the reader toward the climax. The writer also uses interruptions — the driver\u2019s calm explanations — to slow the terror down, making the relief momentary and the fear stronger afterwards. The extract ends by landing, literally and emotionally, at the foot of the castle, so the entire journey becomes a funnel aimed at one building.',
    q4: 'I agree that the landscape is animated until it feels alive. The trees "lean closer as we went", the twilight "merges" into darkness, and the night "lighting little lamps" becomes a purposeful, watching figure. This personification matters because Jonathan\u2019s fear is never of a named enemy — only of place. The writer keeps the source of danger off-stage: the wolves are heard, the dead are only implied, the castle is "ruined" and unlit. By making the environment itself predatory, Stoker traps the character and reader in a world where everything — the soil, the sky, the stones — is potentially hostile, which is precisely the effect he needs for a novel about an ancient evil embedded in the land.',
    q5plan: 'Option: a night journey to somewhere you have never been.\n\nPara 1 — The departure: describe the last familiar landmark disappearing.\nPara 2 — Darkness and unexpected sounds; your reaction (heart, breathing).\nPara 3 — A false alarm — a sound explained — then the real unexplained thing.\nPara 4 — Arrival; describe the place in one final, unsettling image (like the "crouching beast").\n\nThroughout: verbs of movement, similes that compare the journey to a ship at sea, sensory overload then sudden silence.',
  },
  'p1-frankenstein': {
    q2: 'Shelley turns anatomy into horror through contrast. The creature\u2019s features are individually lovely — "lustrous black... flowing" hair, teeth "of a pearly whiteness" — but the conjunction "but" pivots each beauty into repulsion: the skin is "yellow", "scarcely covered" the muscles, the eyes are "watery", "dun-white sockets", "shrivelled complexion... straight black lips". The chiasmus "Beautiful! Great God!" shows Victor\u2019s mind breaking mid-sentence, and the adjectives of decay — "dun", "shrivelled", "dismally" — saturate the passage. The monster is described entirely as a list of parts, never a whole person, so the language itself performs Victor\u2019s failure to see his creation as anything but a catalogue of horrors.',
    q3: 'The structure performs the reversal it describes. It begins at the peak of excitement — "the accomplishment of my toils" — with the creation itself paused in the middle sentence as the eye opens. Shelley then moves into retrospective judgement: the long second paragraph looks back ("How can I describe...") while the third collapses the entire two-year project into a single disillusionment, "the beauty of the dream vanished". Finally, the extract escapes the room with Victor, running, and the pace of the verbs — "rushed", "traversed" — contrasts with the slowness of ruin. The closing dreams in italics of thought leave the horror unfinished, so the structure ends inside Victor\u2019s head, where the creature will stay.',
    q4: 'I agree, but only up to a point. Sympathy is created through Victor\u2019s genuine agony — he has "deprived myself of rest and health" — and through the honesty of his confession: he calls the event a "catastrophe" and blames no one but himself. Yet the language keeps undermining that sympathy: the creature is "the wretch", "the being", "it" — never once "he". Victor\u2019s terror drives him to abandon what he made within minutes of its birth, and the reader senses the cruelty inside the self-pity. The writer therefore creates a complicated sympathy: we pity Victor\u2019s horror, but the passage quietly asks whether horror excuses cruelty. It is the question, more than the answer, that makes the extract powerful.',
    q5plan: 'Option: a long-awaited success turning to disaster.\n\nPara 1 — The final moment of expectation: hands, breath, a countdown, a door about to open.\nPara 2 — Success arrives — describe it in rich, golden language.\nPara 3 — The turn: ONE small detail that is wrong, then another, then the collapse.\nPara 4 — The aftermath: what is left, and what the character feels (contrast with para 2).\n\nThroughout: echo words from the opening at the end; use light/weather as a barometer of feeling.',
  },
  'p2-schools': {
    reading19c: 'Mill argues that memorising facts is not enough: pupils can become "mere parroters" if they repeat other people’s views without thinking. He respects his father’s demanding lessons because his father made him try to find answers for himself, although Mill admits he often failed and that his father could be "very unreasonable" when angry. "Mere parroters" means people who repeat words without understanding them; "furrows traced for them" suggests narrow paths of thought laid down by others. His attitude is reflective rather than simply approving.',
    q2: 'Mill recalls being taught at home by his father, who expected him to work things out for himself: anything he could discover by thinking was withheld until he had tried. He remembers mostly "failures", and his father sometimes showed "displeasure". In Source B, learning changes across a whole school when phones are locked away. The pupil initially laughs at the ban, but later notices that "people’s listening improved" and starts keeping a paper notebook. Mill’s experience centres on demanding one-to-one teaching and independent reasoning; the modern pupil discovers concentration and conversation through a shared school rule.',
    q3: 'The writer uses conversational self-deprecation and concrete detail to sound honest and likeable. The opening claim — "I laughed — genuinely, out loud, in the middle of registration" — establishes a sceptical voice the reader can trust, and the turn "I discovered something awkward: I didn\u2019t know how to do it any more" admits fault, which makes the later praise believable. The simile of collecting phones "like pilots collecting passports" elevates an ordinary routine into something faintly heroic and funny. Single-sentence paragraphs such as "I am not saying the world changed. But the air in our building changed" use sharp contrast to land the argument, as does the final metaphor that the "world is bigger than the size of a screen" — a plain image that makes the conclusion feel inevitable.',
    q4: 'Both writers think young people learn better when they use their own minds. Mill argues against pupils becoming "mere parroters" of other people’s opinions; he contrasts being "crammed with mere facts" with a father who made him think before giving an answer. His retrospective first-person account is candid about his own "failures" and even concedes that his father was "very unreasonable" when angry. The modern pupil also uses first person, but begins with the comic admission that they laughed at the phone ban. Later the writer notices better listening and longer conversations, ending with the image of a world "bigger than the size of a screen". Mill values rigorous independent thought; Source B values attention and social connection. Both use a personal change of mind to make their case.',
    q5plan: 'Article arguing AGAINST phones in schools.\n\nPara 1 — Anecdote: a lesson derailed by a notification; generalize from it.\nPara 2 — Address the counter-argument directly: "Some say phones teach digital skills..." then rebut.\nPara 3 — Evidence-style reasoning: attention, memory, social confidence; the dining-hall test.\nPara 4 — A solution of the middle ground (lockers, pouches, phone-free hours).\nEnd — Rhetorical question + a short, forceful final sentence.\n\nDevices: rule of three, rhetorical questions, direct address ("you know the feeling"), first-person honesty.',
  },
  'p2-weather': {
    reading19c: 'Schlesinger argues that London’s winter fog is oppressive, but that London’s weather should not stand for all of England. He first praises sunnier places and then describes the city air as almost unbreathable. "Spleen" can be inferred from the reference to fog affecting people’s tempers: it means gloom or bad humour here. "Melodramatic ghost" makes the fog seem theatrical as it arrives. His tone mixes genuine discomfort with wit and exaggeration.',
    q2: 'Source A describes London’s winter fog as a problem for breathing and mood: the air is "hardly fit for breathing" and the fog is "thick, full of bad smells". Schlesinger also notices that some places outside London are clear and sunny, so his gloomy experience is specific to the city. Source B describes a city heatwave instead. The tarmac softens, the writer’s home is shut against the heat, and neighbours cannot sleep. While the older writer sees fog as a seasonal hardship, the modern writer connects the heat to a wider problem and asks whether people will change their behaviour.',
    q3: 'The writer personifies the heat into a being that touches, presses and punishes. "A hand pressing on the back of my neck" makes the temperature physical and intimate, while the street that is "holding its breath" turns the city into a single anxious body. Similes built from ordinary life — footprints "like footprints on a beach", curtains "like eyelids", the newspaper "flannel" — root the strangeness in familiar things, which makes it believable. The ending shifts register into plain, declarative sentences: "It does not shout; it simply turns the dial, one notch per summer." The metaphor of the dial compresses the whole argument about climate into one mechanical image, and the closing question hands the responsibility squarely to the reader.',
    q4: 'Both writers find city weather oppressive, but Schlesinger treats it with amused exaggeration while the modern writer turns discomfort into a call for change. Schlesinger says London fog can "surpass all imagining" and compares its arrival to a "melodramatic ghost"; the theatrical simile makes a miserable winter almost entertaining to read about. He contrasts London with sunnier parts of England to challenge the idea that the whole country has the same climate. Source B uses the first-person experience of a heatwave, but ends by admitting "my family still drove two separate cars". Its final question challenges the reader to act. Schlesinger’s travel account describes a city condition; the modern article treats unusual heat as evidence of an urgent environmental problem.',
    q5plan: 'Speech arguing that individuals DO make a difference.\n\nOpening — Address the assembly directly; concede the truth (one person cannot stop a heatwave).\nPara 2 — Reframe: individual choices aggregate — "a million dials turned down, one notch each".\nPara 3 — Concrete examples from daily life (meat-free days, one-car trips, switched-off plugs) with calm verbs, not sermons.\nPara 4 — Answer the strongest counter-argument ("the real polluters are companies") by showing how consumer choices steer them.\nEnd — A repeated refrain phrase + a direct call to one action THIS week.\n\nDevices: rule of three, inclusive pronouns (we, our), anaphora of "when you...", contrast, and a rhetorical question to close.',
  },
  'p2-city': {
    reading19c: 'Engels is initially impressed by London’s docks and ships but turns to the human cost of such a vast city. People pass without looking at one another, though they all want happiness; he calls this "brutal indifference". "Centralisation" means people and trade gathered in one place, while the "world of atoms" imagines individuals separated despite the crowd. His shift from admiration to criticism reveals a concern for human connection.',
    q2: 'Engels describes London as so enormous that a person can walk for hours without seeing open country. Its docks and ships impress him, but its streets are crowded and difficult to move through, and people pass without even a glance. Source B also describes city life among millions of people, yet the writer knew only eleven by name and felt exhausted by noise and slow journeys. In the village of forty-three, life is quieter: the shop closes early and the mobile library becomes an event. Engels sees the city’s scale and isolation; the modern writer finds that a smaller place gives them time to sleep and notice the morning light.',
    q3: 'The writer uses lists and rhythmic exaggeration to make city life feel bruising. The list of what she knows — "five colleagues, four flatmates, a barista called Grace" — is comic precisely because it is so small against "nine million people", and the detail of the neighbour\u2019s name learned "from his post" turns loneliness into a visual joke. The invented condition — "the particular flavour of despair you only taste at 11:40pm on a bus that has not moved for twenty minutes" — compresses time, place and feeling into one phrase. Against this, the village is described with gentle, slowed imagery: silence so complete "I could hear my own blinking", and morning light "down the valley like a poured drink" — language that itself slows the reader down.',
    q4: 'Engels begins by admiring London’s giant docks and the "marvel of England’s greatness", then turns sharply with "But the sacrifices" to condemn the cost of urban growth. His rhetorical questions remind readers that strangers in the crowd share a wish for happiness, while "brutal indifference" shows how the city separates them. The modern writer also sees a city full of people yet knows only eleven by name. Their first-person anecdote uses humour and exact details—the late bus and slow escalators—to make exhaustion personal. Engels argues that the city damages human connection on a social scale; the modern writer chooses to leave and describes the village as a place to recover sleep and time.',
    q5plan: 'Letter arguing city life is NOT bad for you.\n\nOpening — Friendly direct address; establish shared experience ("you remember the flat...").\nPara 2 — Concede: yes, noise, rent and tiredness are real. Be honest, not defensive.\nPara 3 — Counter with what the city gives: anonymity, opportunity, food, ideas, people unlike yourself.\nPara 4 — Balance: it is not city vs country, but how you live in either.\nEnd — Invite them to visit; close warmly with a single striking sentence.\n\nDevices: anecdote, concession-then-rebuttal structure, lists of vivid details, direct address.',
  },
  'p2-work': {
    reading19c: 'Mayhew records a street seller’s account of a week in which he and his wife barely have enough for rent and food. The seller’s daily sums make the hardship concrete, and his final remark that they sometimes "goes without altogether" shows how uncertain their meals are. "Stock-money" is the money needed to buy goods before selling them; "cleared" means the profit left after the cost of those goods. Mayhew’s reporting invites sympathy by letting the seller speak in his own words.',
    q2: 'Both writers show how a small income makes ordinary needs difficult to meet. In Source A, the street seller begins Monday without breakfast and uses his last 8½d. to buy stock. Mayhew calculates a weekly profit of 4s. 3½d., from which the man must pay rent before buying food; he and his wife share half a loaf a day. In Source B, the writer has paid work packing boxes, yet still calculates the price of toast and cannot face the heating bill or a dentist visit. The older seller depends on daily sales and sometimes goes without food altogether. The modern worker describes a quieter chain of bills and choices despite having a job.',
    q3: 'The writer makes low pay tangible through prices and small objects. Exact numbers—eleven pence a slice, "£2.14"—set the terms of a week where everything is arithmetic, and the comparison of running sums to how others "scroll their phones" shows how constant the calculations become. The repeated "I would not" in the heating bill and dentist details shows the decisions the writer keeps postponing. A missing table turns even a cheap purchase into "a decision about what mattered". At the end, the writer reverses the familiar bootstraps phrase by pointing out that "you cannot lift yourself by your own boots", challenging the idea that effort alone can solve poverty.',
    q4: 'Mayhew presents poverty through a real street seller’s voice and a record of his earnings. The day-by-day list of sales makes the uncertainty visible, while Mayhew’s calculation of "4s. 3½d." and the seller’s question about how two people can live on the remainder invite readers to judge the hardship for themselves. Source B is a first-person account of a week packing boxes; everyday details such as toast, bus fare and a missing table show similar pressure in a modern setting. Its closing bootstraps image directly argues that effort alone is insufficient. Both writers use numbers and personal testimony to question easy assumptions about poverty, though Mayhew reports someone else’s experience and the modern writer reflects on their own.',
    q5plan: 'Article agreeing that work must pay enough to live on.\n\nOpening — A striking statistic or a vignette of a working person; state your position in one line.\nPara 2 — Reason one: dignity — work is a contract, not a favour; fair pay is basic decency.\nPara 3 — Reason two: cost to everyone — poverty wages are subsidised by food banks and emergency services; we all pay.\nPara 4 — Address the counter-arguments ("higher wages cost jobs", "businesses can\u2019t afford it") and answer each.\nEnd — A call to action: what readers/employers should do; close on a short, memorable sentence.\n\nDevices: rhetorical questions, rule of three, emotive but precise language, direct address.',
  },
};

MODEL['p2-city-modern-first'] = {
  ...MODEL['p2-city'],
  q2: 'Source A describes a modern worker who leaves a city of nine million for a village of forty-three. The city had people everywhere but few they knew by name, and noise and delays left them exhausted. In the village, the quiet first feels strange, but they can sleep and notice the morning light. Source B also presents a huge city, London, but Engels begins by admiring its docks and ships. He then sees crowds that pass without a glance, which he calls "unfeeling isolation". Both sources show how a large city can leave people disconnected; the modern writer contrasts that life with a village, while Engels examines the city itself.',
  q3: 'Engels first calls London a "strange thing", then piles up the docks, buildings and "countless ships" to show its overwhelming scale. The turn "But the sacrifices" changes admiration into criticism. His rhetorical questions ask why people who share an interest in happiness pass one another "as though they had nothing in common". The phrase "brutal indifference" makes the lack of human contact sound violent, and the final metaphor of a "world of atoms" imagines people as separate particles despite being crowded together. The language moves from spectacle to isolation.',
};

export function exemplarsFor(id) {
  return MODEL[id] || {};
}
