// Sources used by Paper 2 sessions created before source snapshots existed.
// Excluded from the current library; retain for the session expiry window.
export const LEGACY_P2_SOURCES = [
  {
    "id": "p2-schools",
    "textA": "\"NOW, what I want is, Facts. Teach these boys and girls nothing but Facts. Facts alone are wanted in life. Plant nothing else, and root out everything else. You can only form the minds of reasoning animals upon Facts: nothing else will ever be of any service to them. This is the principle on which I bring up my own children, and this is the principle on which I bring up these children. Stick to Facts, sir!\"\n\nThe scene was a plain, bare, monotonous vault of a school-room, and the speaker's square forefinger emphasized his observations by underscoring every sentence with a line on the schoolmaster's sleeve. The emphasis was helped by the speaker's square wall of a forehead, which had his eyebrows for its base, while his eyes found commodious cellarage in two dark caves, overshadowed by the wall.\n\nThe speaker, the schoolmaster, and the third grown person present, all backed a little, and swept with their eyes the inclined plane of little vessels then and there arranged in order, ready to have imperial gallons of facts poured into them until they were full to the brim.\n\n\"Girl number twenty,\" said Mr. Gradgrind, squarely pointing with his square forefinger, \"I don't know that girl. Who is that girl?\"\n\n\"Sissy Jupe, sir,\" explained number twenty, blushing, standing up, and curtseying.\n\n\"Sissy is not a name,\" said Mr. Gradgrind. \"Don't call yourself Sissy. Call yourself Cecilia.\"\n\n\"It's father as calls me Sissy, sir,\" returned the young girl in a trembling voice, and with another curtsey.",
    "textB": "When I first heard that our school was banning phones during lesson time, I laughed — genuinely, out loud, in the middle of registration. The laughter lasted about a week. Then the phones went into a locked pouch at the school gates, and for the first time in years, I had to sit with my own thoughts, and I discovered something awkward: I didn’t know how to do it any more.\n\nEveryone predicted chaos. Instead, something odd happened: people’s listening improved. Conversations in the dining hall ran long and got loud in the way they do when nobody is filming them. Girls who had never spoken in form time started arguing about football, exam nerves, and whether pineapple belongs on pizza. I am not saying the world changed. But the air in our building changed.\n\nThe teachers tell us it is about concentration, and maybe they are right. My grades drifted up by a couple of marks a test, though I’d never admit that to Mr. Davies. But the honest truth is that I have started keeping a notebook, a real paper one, and writing things in it that nobody will ever like.\n\nThere are still days when my pocket feels too light and too empty. But when the bell goes now, my friends and I walk through the gates collecting our phones like pilots collecting passports, and we complain about it loudly, and then we keep talking all the way home. The phones have not gone anywhere. We have simply remembered that the world is bigger than the size of a screen."
  },
  {
    "id": "p2-weather",
    "textA": "Fog everywhere. Fog up the river, where it flows among green aits and meadows; fog down the river, where it rolls defiled among the tiers of shipping and the waterside pollutions of a great (and dirty) city. Fog on the Essex marshes, fog on the Kentish heights. Fog creeping into the cabooses of collier-brigs; fog lying out on the yards and hovering in the rigging of great ships; fog drooping on the gunwales of barges and small boats. Fog in the eyes and throats of ancient Greenwich pensioners, wheezing by the firesides of their wards; fog in the stem and bowl of the afternoon pipe of the wrathful skipper, down in his close cabin; fog cruelly pinching the toes and fingers of his shivering little ’prentice boy on deck. Chance people on the bridges peeping over the parapets into a nether sky of fog, with fog all round them, as if they were up in a balloon and hanging in the misty clouds.\n\nGas looming through the fog in divers places in the streets, much as the sun may, from the spongy fields, be seen to loom by husbandman and ploughboy. Smoke lowering down from chimney-pots, making a soft black drizzle, with flakes of soot in it as big as full-grown snow-flakes — gone into mourning, one might imagine, for the death of the sun.\n\nDogs, undistinguishable in mire. Horses, scarcely better; splashed to their very blinkers. Foot passengers, jostling one another’s umbrellas in a general infection of ill-temper, and losing their foot-hold at street-corners, where tens of thousands of other foot passengers have been slipping and sliding since the day broke.",
    "textB": "On the hottest day of the year, my street went quiet. Not the comfortable quiet of a Sunday morning, but the strange, tight silence of a street holding its breath. The tarmac at the kerb had gone soft; my trainers left damp prints in it like footprints on a beach. Inside, the curtains stayed shut like eyelids, and the fan churned the same warm air around and around, pretending to be helpful.\n\nIn the afternoon I walked to the shop for ice, and the heat was a physical thing, a hand pressing on the back of my neck. An old man sat on a plastic chair in the shade of a bus shelter, holding a damp newspaper to his face like a flannel. \"Thirty-nine, they say,\" he said, as if the nine mattered more than anything had in years. It did, somehow.\n\nThat night nobody could sleep. You could hear it: windows open, radios low, a baby crying at midnight, and an aeroplane dragging its lonely noise from one end of the sky to the other, the same sky the whole city had been staring at all day.\n\nHere is the uncomfortable part, though. We spent a week complaining about the heat, and my family still drove two separate cars to the same supermarket, six minutes apart. A heatwave is a loud event — it interrupts us. Climate change is quiet. It does not shout; it simply turns the dial, one notch per summer, until the unbelievable becomes Wednesday. If a week of forty degrees cannot change how we behave, what can?"
  },
  {
    "id": "p2-city",
    "textA": "For several miles before they reached Milton, they saw a deep lead-coloured cloud hanging over the horizon in the direction in which it lay. It was all the darker from contrast with the pale grey-blue of the wintry sky; for in Heston there had been the earliest signs of frost. Here and there a dark chimney, scattered like needles upon a brown, stubbly plain, sent up its thin puff of smoke; but the cloud hung thick and heavy over the city itself.\n\nNearer to the town, the air had a faint taste and smell of smoke; perhaps, after all, more a loss of the fragrance of grass and herbage than anything else. Every van, every waggon and truck, bore cotton, either in the raw shape of great, heavy bales, or in the perfect form of new-made cloth. The streets were long and straight, the houses small, uniform, and unpicturesque; streets and houses built so precisely alike that you could lose yourself in the town and never find your way again.\n\nThey were within the narrow, crowded streetways of the great city, where everything seemed monotonous and fixed; a pitiless wind whipped the cold dust in their faces, and out of the factory windows the never-ending rattle of the looms came tapping and hammering and clashing through the dirty air. The people who passed had the same look: quick, sharp, and unaccustomed to rest — men with hollow cheeks and unpaid rest behind their eyes, women with shawls pulled tight about them, and children running barefoot through the noise as if it were the only music they knew.",
    "textB": "The leaving was easy, because I never really arrived. For six years I lived in a city of nine million people and I knew eleven of them by name: five colleagues, four flatmates, a barista called Grace, and a man in my building whose name I only learned because it was printed on his post. I was not lonely — that is the strange part. The city was full of company. What I was, was exhausted; tired in a way that no weekend fixed, from the noise, the rent, the escalators that moved slower than my own legs, and the particular flavour of despair you only taste at 11:40pm on a bus that has not moved for twenty minutes.\n\nThe village has forty-three people, two roads, a shop that closes at noon for reasons nobody can explain, and a silence at night so complete that at first I could hear my own blinking.\n\nPeople warned me I would be bored. They were half right. On Tuesday nights the most exciting event in the village is the arrival of the mobile library, which is a van containing a retired teacher named Frank and several thousand books that smell of every kitchen they have ever visited. I am embarrassed to admit that I queue at half past six.\n\nI am not pretending the country is magic. The internet is terrible and the nearest hospital is forty minutes away. But here is the difference: here, I sleep. And in the mornings the light comes down the valley like a poured drink, slow and golden, and — perhaps for the first time in my life — I have time to watch it."
  },
  {
    "id": "p2-work",
    "textA": "The room in which the boys were fed, was a large stone hall, with a copper at one end: out of which the master, dressed in an apron for the occasion, and assisted by one or two women, ladled the gruel at meal-times. Of this festive composition each boy had one porringer, and no more — except on occasions of great public rejoicing, when he had two ounces and a quarter of bread besides. The bowls never wanted washing. The boys polished them with their spoons till they shone again; and when they had performed this operation (which never took very long, the spoons being nearly as large as the bowls), they would sit staring at the copper, with such eager eyes, as if they could have devoured the very bricks of which it was composed.\n\nChild as he was, he was desperate with hunger, and reckless with misery. He rose from the table; and advancing to the master, basin and spoon in hand, said: somewhat alarmed at his own temerity:\n\n\"Please, sir, I want some more.\"\n\nThe master was a fat, healthy man; but he turned very pale. He gazed in stupified astonishment on the small rebel for some seconds, and then clung for support to the copper. The assistants were paralysed with wonder; the boys with fear.\n\n\"For MORE!\" said Mr. Limbkins. \"Compose yourself, Mr. Bumble, and answer me distinctly. Do I understand that he asked for more, after he had eaten the supper allotted by the dietary?\"\n\n\"He did, sir,\" replied Bumble.\n\n\"That boy will be hung,\" said the gentleman in the white waistcoat. \"I know that boy will be hung.\"\n\nNobody in the room doubted it.",
    "textB": "By Thursday, I had become an expert in one thing only: mental arithmetic. Toast costs eleven pence a slice. The bus my agency sent me on costs more than I earned in the first forty minutes of my shift. A tin of tomatoes, a bag of pasta, and a bar of the cheap chocolate that tastes mainly of good intentions: £2.14. I ran these sums the way other people scroll their phones, on a loop, quietly, at the back of my skull.\n\nThe job itself was fine. I packed boxes. The people were kind. It is not poverty of the kind you see in black-and-white films — nobody asked for \"more\", and nobody was refused. But there is a modern version of that same bowl: it is the heating bill you will not open, the dentist you will not call, the flat that has no table because a table, however cheap, is a decision about what matters, and you cannot afford to get that decision wrong.\n\nThe strangest discovery of the week, though, was how the world organises itself around the assumption that you are not poor. The supermarket is full of 3-for-2 offers that save money only if you have it to spend. The mobile library of any high street — the phone — demands insurance, and the insurance demands a bank account, and the account demands an address, and the address demands a deposit.\n\nWe like to tell stories about pulling ourselves up by our bootstraps. It is a good phrase. It is also, I discovered, physically impossible: you cannot lift yourself by your own boots. Somebody, somewhere, always has to reach down a hand."
  }
];
